// this file was generated by the system file generator of cl_matcontL

// this mex function computes the Jacobian matrix of system of ODEs called
//                       "fusion_N_25_cvode_max_ord_1"

#include <math.h>
#include "mex.h"

#define n_parameters 3
#define n_inputs     5
#define n_outputs    1
#define system_size  72

#define input_t 0
#define input_y 1
#define checks false

void fusion_N_25_cvode_max_ord_1_jacobian_params(double* y, double* parameters, double* dydt);

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {

  double parameters[n_parameters];  
  double *y;                      /* 1xN input matrix */
  size_t ncols;                   /* size of matrix */
  double *outMatrix;              /* output matrix */

  /* check for proper number of arguments */
  if(nrhs != n_inputs) {
    mexErrMsgIdAndTxt("fusion_N_25_cvode_max_ord_1_dydt:nrhs","Five inputs required.");
  }
  if(nlhs != n_outputs) {
    mexErrMsgIdAndTxt("fusion_N_25_cvode_max_ord_1_dydt:nlhs","One output required.");
  }


  if ( !mxIsDouble(prhs[input_y]) ) {
    mexErrMsgIdAndTxt("system_fusion_N_25_cvode_max_ord_1:not_double",
                      "Error: Input vector y is not a double.");
  }

  if ( mxGetNumberOfElements(prhs[input_y]) != system_size ) {
    mexErrMsgIdAndTxt("system_fusion_N_25_cvode_max_ord_1:wrong_size",
                     "Input vector y must have 72 elements.");
  }

  for ( int i = 0; i < n_parameters; i++ ) {
    if ( !mxIsDouble(prhs[i + 2]) ) {
      mexErrMsgIdAndTxt("fusion_N_25_cvode_max_ord_1_dydt:not_double",
                        "Error: one of the parameters is not a double");
    } else if ( mxIsComplex(prhs[i + 2]) ) {
      mexErrMsgIdAndTxt("fusion_N_25_cvode_max_ord_1_dydt:not_complex",
                        "Error: one of the parameters not a real number");
    } else if ( mxGetNumberOfElements(prhs[i + 2]) != 1 ) {
      mexErrMsgIdAndTxt("fusion_N_25_cvode_max_ord_1_dydt:notScalar",
                        "Error: one of the parameters is not scalar");
    } else {
      parameters[i] = mxGetScalar(prhs[i+2]);
    }
  }
    
    
  /* create a pointer to the real data in the input matrix  */
  #if MX_HAS_INTERLEAVED_COMPLEX
  y = mxGetDoubles(prhs[input_y]);
  #else
  y = mxGetPr(prhs[input_y]);
  #endif

  /* get dimensions of the input matrix */

  /* create the output matrix */
  plhs[0] = mxCreateDoubleMatrix(system_size, n_parameters, mxREAL);

  /* get a pointer to the real data in the output matrix */
  #if MX_HAS_INTERLEAVED_COMPLEX
  outMatrix = mxGetDoubles(plhs[0]);
  #else
  outMatrix = mxGetPr(plhs[0]);
  #endif

  /* call the computational routine */
  fusion_N_25_cvode_max_ord_1_jacobian_params(y,parameters,outMatrix);
    
}

#define JAC(i,j) jac[(i) + (j) * system_size]

void fusion_N_25_cvode_max_ord_1_jacobian_params(double* y, double* parameters, double* jac) {
  JAC(2,0) =  2.0E+1;
  JAC(5,0) =  2.0E+1;
  JAC(8,0) =  2.0E+1;
  JAC(11,0) =  2.0E+1;
  JAC(14,0) =  2.0E+1;
  JAC(17,0) =  2.0E+1;
  JAC(20,0) =  2.0E+1;
  JAC(23,0) =  2.0E+1;
  JAC(26,0) =  2.0E+1;
  JAC(29,0) =  2.0E+1;
  JAC(32,0) =  2.0E+1;
  JAC(35,0) =  2.0E+1;
  JAC(38,0) =  2.0E+1;
  JAC(41,0) =  2.0E+1;
  JAC(44,0) =  2.0E+1;
  JAC(47,0) =  2.0E+1;
  JAC(50,0) =  2.0E+1;
  JAC(53,0) =  2.0E+1;
  JAC(56,0) =  2.0E+1;
  JAC(59,0) =  2.0E+1;
  JAC(62,0) =  2.0E+1;
  JAC(65,0) =  2.0E+1;
  JAC(68,0) =  2.0E+1;
  JAC(71,0) =  2.0E+1;
  JAC(2,1) =  y[2]*-2.0E+1;
  JAC(5,1) =  y[5]*-2.0E+1;
  JAC(8,1) =  y[8]*-2.0E+1;
  JAC(11,1) =  y[11]*-2.0E+1;
  JAC(14,1) =  y[14]*-2.0E+1;
  JAC(17,1) =  y[17]*-2.0E+1;
  JAC(20,1) =  y[20]*-2.0E+1;
  JAC(23,1) =  y[23]*-2.0E+1;
  JAC(26,1) =  y[26]*-2.0E+1;
  JAC(29,1) =  y[29]*-2.0E+1;
  JAC(32,1) =  y[32]*-2.0E+1;
  JAC(35,1) =  y[35]*-2.0E+1;
  JAC(38,1) =  y[38]*-2.0E+1;
  JAC(41,1) =  y[41]*-2.0E+1;
  JAC(44,1) =  y[44]*-2.0E+1;
  JAC(47,1) =  y[47]*-2.0E+1;
  JAC(50,1) =  y[50]*-2.0E+1;
  JAC(53,1) =  y[53]*-2.0E+1;
  JAC(56,1) =  y[56]*-2.0E+1;
  JAC(59,1) =  y[59]*-2.0E+1;
  JAC(62,1) =  y[62]*-2.0E+1;
  JAC(65,1) =  y[65]*-2.0E+1;
  JAC(68,1) =  y[68]*-2.0E+1;
  JAC(71,1) =  y[71]*-2.0E+1;
  JAC(70,2) =  (((tanh(y[71])*1.499999999925-2.590909090779545)*(y[66]*(-6.286559360228229E-1)+y[69]*6.286559360228229E-1+1.58460140891174E+16/(tanh(y[68]*3.722213807430268E-1-y[71]*1.372221380743027)*6.53648081176093E+16+1.129028503849615E+17))+y[69]*(pow(tanh(y[71]),2.0)*1.499999999925-1.499999999925)*(y[68]*6.286559360228229E-1-y[71]*6.286559360228229E-1))*1.744455854880278E+32)/(y[66]*-5.04701655194055E+32+y[69]*1.86061961505593E+33-y[66]*tanh(y[68]*3.722213807430268E-1-y[71]*1.372221380743027)*2.921956951123477E+32+y[69]*tanh(y[68]*3.722213807430268E-1-y[71]*1.372221380743027)*1.077200829769222E+33+9.086519502890277E+32)+(y[69]*(tanh(y[71])*1.499999999925-2.590909090779545)*3.109818735532921E+32)/(y[66]*-5.04701655194055E+32+y[69]*1.86061961505593E+33-y[66]*tanh(y[68]*3.722213807430268E-1-y[71]*1.372221380743027)*2.921956951123477E+32+y[69]*tanh(y[68]*3.722213807430268E-1-y[71]*1.372221380743027)*1.077200829769222E+33+9.086519502890277E+32)+((tanh(y[71])*(1.1E+1/1.0E+1)-1.9E+1/1.0E+1)*(y[66]*(-6.286559360228229E-1)+y[69]*6.286559360228229E-1+1.58460140891174E+16/(tanh(y[68]*3.722213807430268E-1-y[71]*1.372221380743027)*6.53648081176093E+16+1.129028503849615E+17))*2.616683782189583E+32)/(y[66]*-5.04701655194055E+32+y[69]*1.86061961505593E+33-y[66]*tanh(y[68]*3.722213807430268E-1-y[71]*1.372221380743027)*2.921956951123477E+32+y[69]*tanh(y[68]*3.722213807430268E-1-y[71]*1.372221380743027)*1.077200829769222E+33+9.086519502890277E+32);
  JAC(71,2) =  (-3.140020538784501E+33)/(y[69]*(y[66]*-5.04701655194055E+32+y[69]*1.86061961505593E+33-y[66]*tanh(y[68]*3.722213807430268E-1-y[71]*1.372221380743027)*2.921956951123477E+32+y[69]*tanh(y[68]*3.722213807430268E-1-y[71]*1.372221380743027)*1.077200829769222E+33+9.086519502890277E+32));
}