// this file was generated by the system file generator of cl_matcontL

// this mex function computes the Jacobian matrix of system of ODEs called
//                       "brusselator_1d_N_50"

#include <math.h>
#include "mex.h"

#define n_parameters 5
#define n_inputs     7
#define n_outputs    1
#define system_size  100

#define input_t 0
#define input_y 1
#define checks false

void brusselator_1d_N_50_jacobian_params(double* y, double* parameters, double* dydt);

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {

  double parameters[n_parameters];  
  double *y;                      /* 1xN input matrix */
  size_t ncols;                   /* size of matrix */
  double *outMatrix;              /* output matrix */

  /* check for proper number of arguments */
  if(nrhs != n_inputs) {
    mexErrMsgIdAndTxt("brusselator_1d_N_50_dydt:nrhs","Five inputs required.");
  }
  if(nlhs != n_outputs) {
    mexErrMsgIdAndTxt("brusselator_1d_N_50_dydt:nlhs","One output required.");
  }


  if ( !mxIsDouble(prhs[input_y]) ) {
    mexErrMsgIdAndTxt("system_brusselator_1d_N_50:not_double",
                      "Error: Input vector y is not a double.");
  }

  if ( mxGetNumberOfElements(prhs[input_y]) != system_size ) {
    mexErrMsgIdAndTxt("system_brusselator_1d_N_50:wrong_size",
                     "Input vector y must have 100 elements.");
  }

  for ( int i = 0; i < n_parameters; i++ ) {
    if ( !mxIsDouble(prhs[i + 2]) ) {
      mexErrMsgIdAndTxt("brusselator_1d_N_50_dydt:not_double",
                        "Error: one of the parameters is not a double");
    } else if ( mxIsComplex(prhs[i + 2]) ) {
      mexErrMsgIdAndTxt("brusselator_1d_N_50_dydt:not_complex",
                        "Error: one of the parameters not a real number");
    } else if ( mxGetNumberOfElements(prhs[i + 2]) != 1 ) {
      mexErrMsgIdAndTxt("brusselator_1d_N_50_dydt:notScalar",
                        "Error: one of the parameters is not scalar");
    } else {
      parameters[i] = mxGetScalar(prhs[i+2]);
    }
  }
    
    
  /* create a pointer to the real data in the input matrix  */
  #if MX_HAS_INTERLEAVED_COMPLEX
  y = mxGetDoubles(prhs[input_y]);
  #else
  y = mxGetPr(prhs[input_y]);
  #endif

  /* get dimensions of the input matrix */

  /* create the output matrix */
  plhs[0] = mxCreateDoubleMatrix(system_size, n_parameters, mxREAL);

  /* get a pointer to the real data in the output matrix */
  #if MX_HAS_INTERLEAVED_COMPLEX
  outMatrix = mxGetDoubles(plhs[0]);
  #else
  outMatrix = mxGetPr(plhs[0]);
  #endif

  /* call the computational routine */
  brusselator_1d_N_50_jacobian_params(y,parameters,outMatrix);
    
}

void brusselator_1d_N_50_jacobian_params(double* y, double* parameters, double* jac) {
  jac[0] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(parameters[1]-y[0]*2.0+y[1])*-5.202E+3;
  jac[1] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[0]-y[1]*2.0+y[2])*-5.202E+3;
  jac[2] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[1]-y[2]*2.0+y[3])*-5.202E+3;
  jac[3] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[2]-y[3]*2.0+y[4])*-5.202E+3;
  jac[4] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[3]-y[4]*2.0+y[5])*-5.202E+3;
  jac[5] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[4]-y[5]*2.0+y[6])*-5.202E+3;
  jac[6] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[5]-y[6]*2.0+y[7])*-5.202E+3;
  jac[7] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[6]-y[7]*2.0+y[8])*-5.202E+3;
  jac[8] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[7]-y[8]*2.0+y[9])*-5.202E+3;
  jac[9] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[8]-y[9]*2.0+y[10])*-5.202E+3;
  jac[10] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[9]-y[10]*2.0+y[11])*-5.202E+3;
  jac[11] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[10]-y[11]*2.0+y[12])*-5.202E+3;
  jac[12] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[11]-y[12]*2.0+y[13])*-5.202E+3;
  jac[13] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[12]-y[13]*2.0+y[14])*-5.202E+3;
  jac[14] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[13]-y[14]*2.0+y[15])*-5.202E+3;
  jac[15] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[14]-y[15]*2.0+y[16])*-5.202E+3;
  jac[16] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[15]-y[16]*2.0+y[17])*-5.202E+3;
  jac[17] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[16]-y[17]*2.0+y[18])*-5.202E+3;
  jac[18] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[17]-y[18]*2.0+y[19])*-5.202E+3;
  jac[19] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[18]-y[19]*2.0+y[20])*-5.202E+3;
  jac[20] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[19]-y[20]*2.0+y[21])*-5.202E+3;
  jac[21] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[20]-y[21]*2.0+y[22])*-5.202E+3;
  jac[22] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[21]-y[22]*2.0+y[23])*-5.202E+3;
  jac[23] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[22]-y[23]*2.0+y[24])*-5.202E+3;
  jac[24] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[23]-y[24]*2.0+y[25])*-5.202E+3;
  jac[25] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[24]-y[25]*2.0+y[26])*-5.202E+3;
  jac[26] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[25]-y[26]*2.0+y[27])*-5.202E+3;
  jac[27] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[26]-y[27]*2.0+y[28])*-5.202E+3;
  jac[28] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[27]-y[28]*2.0+y[29])*-5.202E+3;
  jac[29] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[28]-y[29]*2.0+y[30])*-5.202E+3;
  jac[30] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[29]-y[30]*2.0+y[31])*-5.202E+3;
  jac[31] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[30]-y[31]*2.0+y[32])*-5.202E+3;
  jac[32] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[31]-y[32]*2.0+y[33])*-5.202E+3;
  jac[33] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[32]-y[33]*2.0+y[34])*-5.202E+3;
  jac[34] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[33]-y[34]*2.0+y[35])*-5.202E+3;
  jac[35] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[34]-y[35]*2.0+y[36])*-5.202E+3;
  jac[36] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[35]-y[36]*2.0+y[37])*-5.202E+3;
  jac[37] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[36]-y[37]*2.0+y[38])*-5.202E+3;
  jac[38] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[37]-y[38]*2.0+y[39])*-5.202E+3;
  jac[39] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[38]-y[39]*2.0+y[40])*-5.202E+3;
  jac[40] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[39]-y[40]*2.0+y[41])*-5.202E+3;
  jac[41] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[40]-y[41]*2.0+y[42])*-5.202E+3;
  jac[42] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[41]-y[42]*2.0+y[43])*-5.202E+3;
  jac[43] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[42]-y[43]*2.0+y[44])*-5.202E+3;
  jac[44] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[43]-y[44]*2.0+y[45])*-5.202E+3;
  jac[45] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[44]-y[45]*2.0+y[46])*-5.202E+3;
  jac[46] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[45]-y[46]*2.0+y[47])*-5.202E+3;
  jac[47] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[46]-y[47]*2.0+y[48])*-5.202E+3;
  jac[48] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[47]-y[48]*2.0+y[49])*-5.202E+3;
  jac[49] =  parameters[3]*1.0/(parameters[0]*parameters[0]*parameters[0])*(parameters[1]+y[48]-y[49]*2.0)*-5.202E+3;
  jac[50] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[50]*-2.0+y[51]+parameters[2]/parameters[1])*-5.202E+3;
  jac[51] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[50]-y[51]*2.0+y[52])*-5.202E+3;
  jac[52] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[51]-y[52]*2.0+y[53])*-5.202E+3;
  jac[53] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[52]-y[53]*2.0+y[54])*-5.202E+3;
  jac[54] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[53]-y[54]*2.0+y[55])*-5.202E+3;
  jac[55] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[54]-y[55]*2.0+y[56])*-5.202E+3;
  jac[56] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[55]-y[56]*2.0+y[57])*-5.202E+3;
  jac[57] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[56]-y[57]*2.0+y[58])*-5.202E+3;
  jac[58] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[57]-y[58]*2.0+y[59])*-5.202E+3;
  jac[59] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[58]-y[59]*2.0+y[60])*-5.202E+3;
  jac[60] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[59]-y[60]*2.0+y[61])*-5.202E+3;
  jac[61] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[60]-y[61]*2.0+y[62])*-5.202E+3;
  jac[62] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[61]-y[62]*2.0+y[63])*-5.202E+3;
  jac[63] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[62]-y[63]*2.0+y[64])*-5.202E+3;
  jac[64] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[63]-y[64]*2.0+y[65])*-5.202E+3;
  jac[65] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[64]-y[65]*2.0+y[66])*-5.202E+3;
  jac[66] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[65]-y[66]*2.0+y[67])*-5.202E+3;
  jac[67] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[66]-y[67]*2.0+y[68])*-5.202E+3;
  jac[68] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[67]-y[68]*2.0+y[69])*-5.202E+3;
  jac[69] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[68]-y[69]*2.0+y[70])*-5.202E+3;
  jac[70] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[69]-y[70]*2.0+y[71])*-5.202E+3;
  jac[71] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[70]-y[71]*2.0+y[72])*-5.202E+3;
  jac[72] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[71]-y[72]*2.0+y[73])*-5.202E+3;
  jac[73] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[72]-y[73]*2.0+y[74])*-5.202E+3;
  jac[74] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[73]-y[74]*2.0+y[75])*-5.202E+3;
  jac[75] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[74]-y[75]*2.0+y[76])*-5.202E+3;
  jac[76] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[75]-y[76]*2.0+y[77])*-5.202E+3;
  jac[77] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[76]-y[77]*2.0+y[78])*-5.202E+3;
  jac[78] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[77]-y[78]*2.0+y[79])*-5.202E+3;
  jac[79] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[78]-y[79]*2.0+y[80])*-5.202E+3;
  jac[80] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[79]-y[80]*2.0+y[81])*-5.202E+3;
  jac[81] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[80]-y[81]*2.0+y[82])*-5.202E+3;
  jac[82] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[81]-y[82]*2.0+y[83])*-5.202E+3;
  jac[83] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[82]-y[83]*2.0+y[84])*-5.202E+3;
  jac[84] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[83]-y[84]*2.0+y[85])*-5.202E+3;
  jac[85] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[84]-y[85]*2.0+y[86])*-5.202E+3;
  jac[86] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[85]-y[86]*2.0+y[87])*-5.202E+3;
  jac[87] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[86]-y[87]*2.0+y[88])*-5.202E+3;
  jac[88] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[87]-y[88]*2.0+y[89])*-5.202E+3;
  jac[89] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[88]-y[89]*2.0+y[90])*-5.202E+3;
  jac[90] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[89]-y[90]*2.0+y[91])*-5.202E+3;
  jac[91] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[90]-y[91]*2.0+y[92])*-5.202E+3;
  jac[92] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[91]-y[92]*2.0+y[93])*-5.202E+3;
  jac[93] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[92]-y[93]*2.0+y[94])*-5.202E+3;
  jac[94] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[93]-y[94]*2.0+y[95])*-5.202E+3;
  jac[95] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[94]-y[95]*2.0+y[96])*-5.202E+3;
  jac[96] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[95]-y[96]*2.0+y[97])*-5.202E+3;
  jac[97] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[96]-y[97]*2.0+y[98])*-5.202E+3;
  jac[98] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[97]-y[98]*2.0+y[99])*-5.202E+3;
  jac[99] =  parameters[4]*1.0/(parameters[0]*parameters[0]*parameters[0])*(y[98]-y[99]*2.0+parameters[2]/parameters[1])*-5.202E+3;
  jac[100] =  parameters[3]*1.0/(parameters[0]*parameters[0])*2.601E+3+1.0;
  jac[101] =  1.0;
  jac[102] =  1.0;
  jac[103] =  1.0;
  jac[104] =  1.0;
  jac[105] =  1.0;
  jac[106] =  1.0;
  jac[107] =  1.0;
  jac[108] =  1.0;
  jac[109] =  1.0;
  jac[110] =  1.0;
  jac[111] =  1.0;
  jac[112] =  1.0;
  jac[113] =  1.0;
  jac[114] =  1.0;
  jac[115] =  1.0;
  jac[116] =  1.0;
  jac[117] =  1.0;
  jac[118] =  1.0;
  jac[119] =  1.0;
  jac[120] =  1.0;
  jac[121] =  1.0;
  jac[122] =  1.0;
  jac[123] =  1.0;
  jac[124] =  1.0;
  jac[125] =  1.0;
  jac[126] =  1.0;
  jac[127] =  1.0;
  jac[128] =  1.0;
  jac[129] =  1.0;
  jac[130] =  1.0;
  jac[131] =  1.0;
  jac[132] =  1.0;
  jac[133] =  1.0;
  jac[134] =  1.0;
  jac[135] =  1.0;
  jac[136] =  1.0;
  jac[137] =  1.0;
  jac[138] =  1.0;
  jac[139] =  1.0;
  jac[140] =  1.0;
  jac[141] =  1.0;
  jac[142] =  1.0;
  jac[143] =  1.0;
  jac[144] =  1.0;
  jac[145] =  1.0;
  jac[146] =  1.0;
  jac[147] =  1.0;
  jac[148] =  1.0;
  jac[149] =  parameters[3]*1.0/(parameters[0]*parameters[0])*2.601E+3+1.0;
  jac[150] =  1.0/(parameters[1]*parameters[1])*parameters[2]*parameters[4]*1.0/(parameters[0]*parameters[0])*-2.601E+3;
  jac[199] =  1.0/(parameters[1]*parameters[1])*parameters[2]*parameters[4]*1.0/(parameters[0]*parameters[0])*-2.601E+3;
  jac[200] =  -y[0];
  jac[201] =  -y[1];
  jac[202] =  -y[2];
  jac[203] =  -y[3];
  jac[204] =  -y[4];
  jac[205] =  -y[5];
  jac[206] =  -y[6];
  jac[207] =  -y[7];
  jac[208] =  -y[8];
  jac[209] =  -y[9];
  jac[210] =  -y[10];
  jac[211] =  -y[11];
  jac[212] =  -y[12];
  jac[213] =  -y[13];
  jac[214] =  -y[14];
  jac[215] =  -y[15];
  jac[216] =  -y[16];
  jac[217] =  -y[17];
  jac[218] =  -y[18];
  jac[219] =  -y[19];
  jac[220] =  -y[20];
  jac[221] =  -y[21];
  jac[222] =  -y[22];
  jac[223] =  -y[23];
  jac[224] =  -y[24];
  jac[225] =  -y[25];
  jac[226] =  -y[26];
  jac[227] =  -y[27];
  jac[228] =  -y[28];
  jac[229] =  -y[29];
  jac[230] =  -y[30];
  jac[231] =  -y[31];
  jac[232] =  -y[32];
  jac[233] =  -y[33];
  jac[234] =  -y[34];
  jac[235] =  -y[35];
  jac[236] =  -y[36];
  jac[237] =  -y[37];
  jac[238] =  -y[38];
  jac[239] =  -y[39];
  jac[240] =  -y[40];
  jac[241] =  -y[41];
  jac[242] =  -y[42];
  jac[243] =  -y[43];
  jac[244] =  -y[44];
  jac[245] =  -y[45];
  jac[246] =  -y[46];
  jac[247] =  -y[47];
  jac[248] =  -y[48];
  jac[249] =  -y[49];
  jac[250] =  y[0]+(parameters[4]*1.0/(parameters[0]*parameters[0])*2.601E+3)/parameters[1];
  jac[251] =  y[1];
  jac[252] =  y[2];
  jac[253] =  y[3];
  jac[254] =  y[4];
  jac[255] =  y[5];
  jac[256] =  y[6];
  jac[257] =  y[7];
  jac[258] =  y[8];
  jac[259] =  y[9];
  jac[260] =  y[10];
  jac[261] =  y[11];
  jac[262] =  y[12];
  jac[263] =  y[13];
  jac[264] =  y[14];
  jac[265] =  y[15];
  jac[266] =  y[16];
  jac[267] =  y[17];
  jac[268] =  y[18];
  jac[269] =  y[19];
  jac[270] =  y[20];
  jac[271] =  y[21];
  jac[272] =  y[22];
  jac[273] =  y[23];
  jac[274] =  y[24];
  jac[275] =  y[25];
  jac[276] =  y[26];
  jac[277] =  y[27];
  jac[278] =  y[28];
  jac[279] =  y[29];
  jac[280] =  y[30];
  jac[281] =  y[31];
  jac[282] =  y[32];
  jac[283] =  y[33];
  jac[284] =  y[34];
  jac[285] =  y[35];
  jac[286] =  y[36];
  jac[287] =  y[37];
  jac[288] =  y[38];
  jac[289] =  y[39];
  jac[290] =  y[40];
  jac[291] =  y[41];
  jac[292] =  y[42];
  jac[293] =  y[43];
  jac[294] =  y[44];
  jac[295] =  y[45];
  jac[296] =  y[46];
  jac[297] =  y[47];
  jac[298] =  y[48];
  jac[299] =  y[49]+(parameters[4]*1.0/(parameters[0]*parameters[0])*2.601E+3)/parameters[1];
  jac[300] =  1.0/(parameters[0]*parameters[0])*(parameters[1]-y[0]*2.0+y[1])*2.601E+3;
  jac[301] =  1.0/(parameters[0]*parameters[0])*(y[0]-y[1]*2.0+y[2])*2.601E+3;
  jac[302] =  1.0/(parameters[0]*parameters[0])*(y[1]-y[2]*2.0+y[3])*2.601E+3;
  jac[303] =  1.0/(parameters[0]*parameters[0])*(y[2]-y[3]*2.0+y[4])*2.601E+3;
  jac[304] =  1.0/(parameters[0]*parameters[0])*(y[3]-y[4]*2.0+y[5])*2.601E+3;
  jac[305] =  1.0/(parameters[0]*parameters[0])*(y[4]-y[5]*2.0+y[6])*2.601E+3;
  jac[306] =  1.0/(parameters[0]*parameters[0])*(y[5]-y[6]*2.0+y[7])*2.601E+3;
  jac[307] =  1.0/(parameters[0]*parameters[0])*(y[6]-y[7]*2.0+y[8])*2.601E+3;
  jac[308] =  1.0/(parameters[0]*parameters[0])*(y[7]-y[8]*2.0+y[9])*2.601E+3;
  jac[309] =  1.0/(parameters[0]*parameters[0])*(y[8]-y[9]*2.0+y[10])*2.601E+3;
  jac[310] =  1.0/(parameters[0]*parameters[0])*(y[9]-y[10]*2.0+y[11])*2.601E+3;
  jac[311] =  1.0/(parameters[0]*parameters[0])*(y[10]-y[11]*2.0+y[12])*2.601E+3;
  jac[312] =  1.0/(parameters[0]*parameters[0])*(y[11]-y[12]*2.0+y[13])*2.601E+3;
  jac[313] =  1.0/(parameters[0]*parameters[0])*(y[12]-y[13]*2.0+y[14])*2.601E+3;
  jac[314] =  1.0/(parameters[0]*parameters[0])*(y[13]-y[14]*2.0+y[15])*2.601E+3;
  jac[315] =  1.0/(parameters[0]*parameters[0])*(y[14]-y[15]*2.0+y[16])*2.601E+3;
  jac[316] =  1.0/(parameters[0]*parameters[0])*(y[15]-y[16]*2.0+y[17])*2.601E+3;
  jac[317] =  1.0/(parameters[0]*parameters[0])*(y[16]-y[17]*2.0+y[18])*2.601E+3;
  jac[318] =  1.0/(parameters[0]*parameters[0])*(y[17]-y[18]*2.0+y[19])*2.601E+3;
  jac[319] =  1.0/(parameters[0]*parameters[0])*(y[18]-y[19]*2.0+y[20])*2.601E+3;
  jac[320] =  1.0/(parameters[0]*parameters[0])*(y[19]-y[20]*2.0+y[21])*2.601E+3;
  jac[321] =  1.0/(parameters[0]*parameters[0])*(y[20]-y[21]*2.0+y[22])*2.601E+3;
  jac[322] =  1.0/(parameters[0]*parameters[0])*(y[21]-y[22]*2.0+y[23])*2.601E+3;
  jac[323] =  1.0/(parameters[0]*parameters[0])*(y[22]-y[23]*2.0+y[24])*2.601E+3;
  jac[324] =  1.0/(parameters[0]*parameters[0])*(y[23]-y[24]*2.0+y[25])*2.601E+3;
  jac[325] =  1.0/(parameters[0]*parameters[0])*(y[24]-y[25]*2.0+y[26])*2.601E+3;
  jac[326] =  1.0/(parameters[0]*parameters[0])*(y[25]-y[26]*2.0+y[27])*2.601E+3;
  jac[327] =  1.0/(parameters[0]*parameters[0])*(y[26]-y[27]*2.0+y[28])*2.601E+3;
  jac[328] =  1.0/(parameters[0]*parameters[0])*(y[27]-y[28]*2.0+y[29])*2.601E+3;
  jac[329] =  1.0/(parameters[0]*parameters[0])*(y[28]-y[29]*2.0+y[30])*2.601E+3;
  jac[330] =  1.0/(parameters[0]*parameters[0])*(y[29]-y[30]*2.0+y[31])*2.601E+3;
  jac[331] =  1.0/(parameters[0]*parameters[0])*(y[30]-y[31]*2.0+y[32])*2.601E+3;
  jac[332] =  1.0/(parameters[0]*parameters[0])*(y[31]-y[32]*2.0+y[33])*2.601E+3;
  jac[333] =  1.0/(parameters[0]*parameters[0])*(y[32]-y[33]*2.0+y[34])*2.601E+3;
  jac[334] =  1.0/(parameters[0]*parameters[0])*(y[33]-y[34]*2.0+y[35])*2.601E+3;
  jac[335] =  1.0/(parameters[0]*parameters[0])*(y[34]-y[35]*2.0+y[36])*2.601E+3;
  jac[336] =  1.0/(parameters[0]*parameters[0])*(y[35]-y[36]*2.0+y[37])*2.601E+3;
  jac[337] =  1.0/(parameters[0]*parameters[0])*(y[36]-y[37]*2.0+y[38])*2.601E+3;
  jac[338] =  1.0/(parameters[0]*parameters[0])*(y[37]-y[38]*2.0+y[39])*2.601E+3;
  jac[339] =  1.0/(parameters[0]*parameters[0])*(y[38]-y[39]*2.0+y[40])*2.601E+3;
  jac[340] =  1.0/(parameters[0]*parameters[0])*(y[39]-y[40]*2.0+y[41])*2.601E+3;
  jac[341] =  1.0/(parameters[0]*parameters[0])*(y[40]-y[41]*2.0+y[42])*2.601E+3;
  jac[342] =  1.0/(parameters[0]*parameters[0])*(y[41]-y[42]*2.0+y[43])*2.601E+3;
  jac[343] =  1.0/(parameters[0]*parameters[0])*(y[42]-y[43]*2.0+y[44])*2.601E+3;
  jac[344] =  1.0/(parameters[0]*parameters[0])*(y[43]-y[44]*2.0+y[45])*2.601E+3;
  jac[345] =  1.0/(parameters[0]*parameters[0])*(y[44]-y[45]*2.0+y[46])*2.601E+3;
  jac[346] =  1.0/(parameters[0]*parameters[0])*(y[45]-y[46]*2.0+y[47])*2.601E+3;
  jac[347] =  1.0/(parameters[0]*parameters[0])*(y[46]-y[47]*2.0+y[48])*2.601E+3;
  jac[348] =  1.0/(parameters[0]*parameters[0])*(y[47]-y[48]*2.0+y[49])*2.601E+3;
  jac[349] =  1.0/(parameters[0]*parameters[0])*(parameters[1]+y[48]-y[49]*2.0)*2.601E+3;
  jac[450] =  1.0/(parameters[0]*parameters[0])*(y[50]*-2.0+y[51]+parameters[2]/parameters[1])*2.601E+3;
  jac[451] =  1.0/(parameters[0]*parameters[0])*(y[50]-y[51]*2.0+y[52])*2.601E+3;
  jac[452] =  1.0/(parameters[0]*parameters[0])*(y[51]-y[52]*2.0+y[53])*2.601E+3;
  jac[453] =  1.0/(parameters[0]*parameters[0])*(y[52]-y[53]*2.0+y[54])*2.601E+3;
  jac[454] =  1.0/(parameters[0]*parameters[0])*(y[53]-y[54]*2.0+y[55])*2.601E+3;
  jac[455] =  1.0/(parameters[0]*parameters[0])*(y[54]-y[55]*2.0+y[56])*2.601E+3;
  jac[456] =  1.0/(parameters[0]*parameters[0])*(y[55]-y[56]*2.0+y[57])*2.601E+3;
  jac[457] =  1.0/(parameters[0]*parameters[0])*(y[56]-y[57]*2.0+y[58])*2.601E+3;
  jac[458] =  1.0/(parameters[0]*parameters[0])*(y[57]-y[58]*2.0+y[59])*2.601E+3;
  jac[459] =  1.0/(parameters[0]*parameters[0])*(y[58]-y[59]*2.0+y[60])*2.601E+3;
  jac[460] =  1.0/(parameters[0]*parameters[0])*(y[59]-y[60]*2.0+y[61])*2.601E+3;
  jac[461] =  1.0/(parameters[0]*parameters[0])*(y[60]-y[61]*2.0+y[62])*2.601E+3;
  jac[462] =  1.0/(parameters[0]*parameters[0])*(y[61]-y[62]*2.0+y[63])*2.601E+3;
  jac[463] =  1.0/(parameters[0]*parameters[0])*(y[62]-y[63]*2.0+y[64])*2.601E+3;
  jac[464] =  1.0/(parameters[0]*parameters[0])*(y[63]-y[64]*2.0+y[65])*2.601E+3;
  jac[465] =  1.0/(parameters[0]*parameters[0])*(y[64]-y[65]*2.0+y[66])*2.601E+3;
  jac[466] =  1.0/(parameters[0]*parameters[0])*(y[65]-y[66]*2.0+y[67])*2.601E+3;
  jac[467] =  1.0/(parameters[0]*parameters[0])*(y[66]-y[67]*2.0+y[68])*2.601E+3;
  jac[468] =  1.0/(parameters[0]*parameters[0])*(y[67]-y[68]*2.0+y[69])*2.601E+3;
  jac[469] =  1.0/(parameters[0]*parameters[0])*(y[68]-y[69]*2.0+y[70])*2.601E+3;
  jac[470] =  1.0/(parameters[0]*parameters[0])*(y[69]-y[70]*2.0+y[71])*2.601E+3;
  jac[471] =  1.0/(parameters[0]*parameters[0])*(y[70]-y[71]*2.0+y[72])*2.601E+3;
  jac[472] =  1.0/(parameters[0]*parameters[0])*(y[71]-y[72]*2.0+y[73])*2.601E+3;
  jac[473] =  1.0/(parameters[0]*parameters[0])*(y[72]-y[73]*2.0+y[74])*2.601E+3;
  jac[474] =  1.0/(parameters[0]*parameters[0])*(y[73]-y[74]*2.0+y[75])*2.601E+3;
  jac[475] =  1.0/(parameters[0]*parameters[0])*(y[74]-y[75]*2.0+y[76])*2.601E+3;
  jac[476] =  1.0/(parameters[0]*parameters[0])*(y[75]-y[76]*2.0+y[77])*2.601E+3;
  jac[477] =  1.0/(parameters[0]*parameters[0])*(y[76]-y[77]*2.0+y[78])*2.601E+3;
  jac[478] =  1.0/(parameters[0]*parameters[0])*(y[77]-y[78]*2.0+y[79])*2.601E+3;
  jac[479] =  1.0/(parameters[0]*parameters[0])*(y[78]-y[79]*2.0+y[80])*2.601E+3;
  jac[480] =  1.0/(parameters[0]*parameters[0])*(y[79]-y[80]*2.0+y[81])*2.601E+3;
  jac[481] =  1.0/(parameters[0]*parameters[0])*(y[80]-y[81]*2.0+y[82])*2.601E+3;
  jac[482] =  1.0/(parameters[0]*parameters[0])*(y[81]-y[82]*2.0+y[83])*2.601E+3;
  jac[483] =  1.0/(parameters[0]*parameters[0])*(y[82]-y[83]*2.0+y[84])*2.601E+3;
  jac[484] =  1.0/(parameters[0]*parameters[0])*(y[83]-y[84]*2.0+y[85])*2.601E+3;
  jac[485] =  1.0/(parameters[0]*parameters[0])*(y[84]-y[85]*2.0+y[86])*2.601E+3;
  jac[486] =  1.0/(parameters[0]*parameters[0])*(y[85]-y[86]*2.0+y[87])*2.601E+3;
  jac[487] =  1.0/(parameters[0]*parameters[0])*(y[86]-y[87]*2.0+y[88])*2.601E+3;
  jac[488] =  1.0/(parameters[0]*parameters[0])*(y[87]-y[88]*2.0+y[89])*2.601E+3;
  jac[489] =  1.0/(parameters[0]*parameters[0])*(y[88]-y[89]*2.0+y[90])*2.601E+3;
  jac[490] =  1.0/(parameters[0]*parameters[0])*(y[89]-y[90]*2.0+y[91])*2.601E+3;
  jac[491] =  1.0/(parameters[0]*parameters[0])*(y[90]-y[91]*2.0+y[92])*2.601E+3;
  jac[492] =  1.0/(parameters[0]*parameters[0])*(y[91]-y[92]*2.0+y[93])*2.601E+3;
  jac[493] =  1.0/(parameters[0]*parameters[0])*(y[92]-y[93]*2.0+y[94])*2.601E+3;
  jac[494] =  1.0/(parameters[0]*parameters[0])*(y[93]-y[94]*2.0+y[95])*2.601E+3;
  jac[495] =  1.0/(parameters[0]*parameters[0])*(y[94]-y[95]*2.0+y[96])*2.601E+3;
  jac[496] =  1.0/(parameters[0]*parameters[0])*(y[95]-y[96]*2.0+y[97])*2.601E+3;
  jac[497] =  1.0/(parameters[0]*parameters[0])*(y[96]-y[97]*2.0+y[98])*2.601E+3;
  jac[498] =  1.0/(parameters[0]*parameters[0])*(y[97]-y[98]*2.0+y[99])*2.601E+3;
  jac[499] =  1.0/(parameters[0]*parameters[0])*(y[98]-y[99]*2.0+parameters[2]/parameters[1])*2.601E+3;
}