function thyroid_intermediate_expressions

  % Thyroid_2d_constants
  constants = { ...
    'c1',   '0.1', ...
    'c2',   '0.4', ...
    'V1',   '3.4e-12', ...
    'K1',   '2.75', ...
    'V2',   '1e-10', ...
    'K2',   '1e-9', ...
    's1',   '2.41692e2', ...
    'e1',   '140', ...
    's2',   '1e-18', ...
    'e2',   '1.1e-6', ...
    'sc2',  '5.7925', ...
    'sc3',  '1.000260643477599e+00', ...
    'y1',   '1', ...		% scaling in a normal case
    'y2',   '1.5e-11'}; % scaling in a normal case

  equations  = {
    'v1n = sc1 * V1 * y1 * TSHn / (K1 + y1*TSHn)'
    'v2n = V2 * y2 * FT4n / (K2 + y2 * FT4n)'
    'TSHn'' = c1*(( -v1n + k1 * v2n) + sc2 * s1)/y1 -       e1 * TSHn'
    'FT4n'' = c2*(( -v2n + k2 * v1n) +       s2)/y2 - sc3 * e2 * FT4n'
  };

  names_of_constants  = constants(1:2:end);
  values_of_constants = constants(2:2:end);

  for i = 1 : length(equations)
    equations{i} = replace_symbols(equations{i}, names_of_constants, ...
                                                 values_of_constants);
  end

  name = 'Thyroid_2d1';
  pars = 'k1 k2 sc1';
  max_ord = 1;
  my_sys = SystemFileGenerator.new(name, pars, 't', max_ord, equations);

  disp(my_sys);

  my_sys.generate_file()
end