% continuation of cycles in fusion system.
clc
clear global
N = 75;                     
odefile = str2func(sprintf('fusion_precomputed_with_sage_N_%d', N));
a = -1;
b = -0.3;  
q_inf = -0.72;

ode_parameters = {a ; b; q_inf};


initial_continuation_data = init_collocation_find_stable_cycle( ...
  'initial_point',             ones(3*(N-1),1), ...
  'time_to_converge_to_cycle', 150, ... 
  'odefile',                   odefile,  ...
  'ode_parameters',            ode_parameters, ...
  'active_parameter_index',    3, ...
  'lower_bound_period',        1, ...
  'upper_bound_period',        20, ...
  'nMeshIntervals',            80, ...
  'show_plots',                 false ...
);

options = contset( ...
  'MaxNumPoints',            2000, ...
  'InitStepsize',            1, ...
  'MinStepsize',             1e-6, ...
  'MaxStepsize',             1, ...
  'MaxNewtonIters',          8, ...
  'MaxCorrIters',            10, ...
  'MaxTestIters',            10, ...
  'Backward',                false, ...
  'VarTolerance',            1e-4, ...
  'FunTolerance',            1e-4, ...
  'Adapt',                   3, ...
  'Multipliers',             true, ...
  'Singularities',           true, ...
  'MoorePenrose',            false, ...
  'contL_SmoothingAngle',    6 / 180 * pi, ...
  'console_output_level',    3, ...
  'contL_DiagnosticsLevel',  3, ...
  'enable_nf_pd',            false, ...
  'enable_nf_lpc',           false, ...
  'enable_nf_ns',            false, ...
  'multiplier_print_threshold', 0.99);

contL(@limitcycleL, initial_continuation_data, [], options, ...
                   'callback', @plot_T_versus_param);