function writeConfigurationFile(rel_name,use_default_eigs)
%   writeConfigurationFile:
%       This routine creates the version-specific configuration file for
%       eigsPlus.  The file is created in this directory.  The
%       configuration file determines whether eigsPlus should use its
%       modified version of the eigs source (the default behavior) or if it
%       should use the default eigs routine (presumably for compatability
%       reasons).
%
%   USAGE:
%       writeConfigurationFile(rel_name)
%       writeConfigurationFile(rel_name,use_default_eigs)
% 
%   INPUT:
%       rel_name            'XXXXX' string for the Matlab release 
%                           (e.g. 2016b)
%   
%       use_default_eigs    logical indicating how whether or not the 
%                           configuration routine should be written so that
%                           eigsPlus will use:
%
%                           its modified source (use_default_eigs == false)
%                           the default eigs    (use_default_eigs == true)
%
%                           If use_default_eigs is not provided, it is
%                           assumed to be false.
%   
%
%   For comments/bug reports, please visit the eigsPlus GitLab webpage:
%   https://gitlab.com/timmitchell/eigsPlus
%
%   writeConfigurationFile.m introduced in eigsPlus Version 2.0.
%
% =========================================================================
% |  eigsPlus                                                             |
% |  Copyright (C) 2016 Tim Mitchell                                      |
% |                                                                       |
% |  This file is part of eigsPlus.                                       |
% |                                                                       |
% |  eigsPlus is free software: you can redistribute it and/or modify     |
% |  it under the terms of the GNU Affero General Public License as       |
% |  published by the Free Software Foundation, either version 3 of       |
% |  the License, or (at your option) any later version.                  |
% |                                                                       |
% |  eigsPlus is distributed in the hope that it will be useful,          |
% |  but WITHOUT ANY WARRANTY; without even the implied warranty of       |
% |  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        |
% |  GNU Affero General Public License for more details.                  |
% |                                                                       |
% |  You should have received a copy of the GNU Affero General Public     |
% |  License along with this program.  If not, see                        |
% |  <http://www.gnu.org/licenses/>.                                      |
% =========================================================================

    fn_filename = getUseDefaultEigsName(rel_name);

    signature   = ['function tf = ' fn_filename(1:end-2) '()\n'];
    doc_line    = '%% eigsPlus autogenerated code.\n';
    if nargin < 2 || ~use_default_eigs
        line    = '    tf = false;\n';
    else
        line    = '    tf = true;\n';
    end
   
    code = [signature doc_line line 'end\n'];
    
    base_path           = fileparts(mfilename('fullpath'));
    fn_filename         = [base_path filesep fn_filename];
    
    [fileID,err_msg] = fopen(fn_filename,'w');
    if ~isempty(err_msg)
        error(  'makeEigsPlus:writeConfigurationFile',                  ...
                [   'Failed to write eigsPlus configuration file. \n'   ...
                    'Error message:\n%s\n'                              ...
                    'Make sure the "private" subfolder of eigsPlus''s ' ...
                    'installation directory has its write permissions ' ...
                    'enabled.'  ], err_msg                              );
    end
    fprintf(fileID,code);
    status = fclose(fileID);
    if status ~= 0
        error(  'makeEigsPlus:writeConfigurationFile',                  ...
                [   'Failed to close file after writing eigsPlus''s '   ...
                    'configuration file.  Are you sure your machine '   ...
                    'is okay???'    ]                                   );
    end
end