// this file was generated by the system file generator of cl_matcontL

// this mex function computes the Jacobian of system of ODEs with respect to the
// parameters fo the system of ODEs. The name of the system of ODEs is:
//
//                       "bpros273_cvode_sp"

#include <math.h>
#include "mex.h"
#include "mex_utils.c"

#define N_PARAMETERS        1
#define REQUIRED_N_INPUTS   3
#define SYSTEM_SIZE         273

#define INPUT_T 0
#define INPUT_Y 1
#define JAC(i,j) jac[(i) + (j) * SYSTEM_SIZE]

void mexFunction(int n_outputs,       mxArray *outputs[], 
                 int n_inputs , const mxArray *inputs []) {

  check_n_inputs(n_inputs, REQUIRED_N_INPUTS, "jacobian_params_mex");

  double *y = get_doubles(inputs[INPUT_Y], "Input vector y", SYSTEM_SIZE);

  double parameters[N_PARAMETERS];  
  get_parameters(inputs, parameters, N_PARAMETERS);
    
  outputs[0] = mxCreateDoubleMatrix(SYSTEM_SIZE, N_PARAMETERS, mxREAL);
  double* jac = my_mex_get_doubles(outputs[0]);

  JAC(268,0) =  y[269]*(3.9E+1/2.0E+2)+7.15709E-1;
  JAC(269,0) =  y[269]*(-3.9E+1/2.0E+2);
}
