nSessions = 30;

filename                   = 'bruss_ss';
path_to_cl_matcontL_script = get_path();
script                     = 'extend_bruss_single_shooting';


for i=3:nSessions
  session_filename = [filename '_' num2str(i)];
  exec_string = sprintf([ 
    'matlab -nojvm -r "', ...
      'try;'...
        'cd /home/carel/Documents/cl_matcontL;', ...
        'init;', ...
        sprintf('session_filename = ''%s'';', session_filename), ...
        sprintf('cd ''%s'';', path_to_cl_matcontL_script), ...
        script ';', ...
      'catch e;', ...
        'disp(e.message);', ...
        'disp(e.stack);', ...
        'quit(1);', ...
      'end;', ...
      'quit;"']);
  errorlevel = system(exec_string);
  if errorlevel >= 1
    break
  end
  cd Data
  cd(session_filename)
  system 'cp `ls -t | head -n1` ../most_recent_point.mat'
  cd ..
  cd ..
end