function initialize_lds_fields

  global lds
  lds_fieldnames = { ...
     'odefile'         , ...
     'func'            , ...
     'Jacobian'        , ...
     'JacobianP'       , ...
     'Hessians'        , ...
     'HessiansP'       , ...
     'Der3'            , ...
     'Der4'            , ...
     'Der5'            , ...
     'user'            , ...
     'nphase'          , ...
     'ActiveParams'    , ...
     'P0'              , ...
     'ntst'            , ...
     'ncol'            , ...
     'tsts'            , ...
     'cols'            , ...
     'tps'             , ...
     'ncoords'         , ...
     'coords'          , ...
     'PeriodIdx'       , ...
     'idxmat'          , ...
     'msh'             , ...
     'finemsh'         , ...
     'dt'              , ...
     'upoldp'          , ...
     'multipliersX'    , ...
     'CalcMultipliers' , ...
     'wi'              , ...
     'wt'              , ...
     'wpvec'           , ...
     'T'               , ...
     'cols_p1'         , ...
     'cols_p1_coords'  , ...
     'ncol_coord'      , ...
     'col_coords'      , ...
     'pars'            , ...
     'phases'          , ...
     'ntstcol'         , ...
     'wp'              , ...
     'pwwt'            , ...
     'pwi'             , ...
     'PD_psi'          , ...
     'PD_phi'          , ...
     'PD_new_phi'      , ...
     'PD_new_psi'      , ...
     'PD_switch'       , ...
     'BP_psi'          , ...
     'BP_phi'          , ...
     'BP_psi1'         , ...
     'BP_phi1'         , ...
     'BP_new_phi'      , ...
     'BP_new_psi'      , ...
     'BP_new_psi1'     , ...
     'BP_new_phi1'     , ...
     'BP_switch'       , ...
     'BPC_switch'      , ...
     'BPC_psi'         , ...
     'BPC_phi1'        , ...
     'BPC_phi2'        , ...
     'LPC_phi'         , ...
     'LPC_psi'         , ...
     'LPC_new_phi'     , ...
     'LPC_new_psi'     , ...
     'LPC_switch'      , ...
     'NS_psi0'         , ...
     'NS_psi1'         , ...
     'NS_phi0'         , ...
     'NS_phi1'         , ...
     'NS1_new_phi'     , ...
     'NS2_new_phi'     , ...
     'NS1_new_psi'     , ...
     'NS2_new_psi'     , ...
     'NS_new_phi'      , ...
     'NS_new_psi'      , ...
     'NS_switch'       , ...
     'NS1_switch'      , ...
     'NS2_switch'      , ...
     'bialt_M1'        , ...
     'bialt_M2'        , ...
     'bialt_M3'       , ...
     'bialt_M4'       , ...
     'multipliers'    , ...
     'monodromy'      , ...
     'multi_r1'       , ...
     'multi_r2'       , ...
     'BranchParam'    , ...
     'ups'            , ...
     'vps'            , ...
     'BranchParams'   , ...
     'CalcPRC'        , ...
     'CalcdPRC'       , ...
     'PRCInput'       , ...
     'PRCdata'        , ...
     'dPRCdata'       };
   
   
   for i = 1:length(lds_fieldnames)
     lds.(lds_fieldnames{i}) = [];
   end
end
