function multipliers = compute_multipliers(x, nMults_to_compute)
  global cds contopts;
  print_diag(3,'computing multipliers\n');
  [phases, period, parameters] = ...
    NewtonPicard.SingleShooting.extract_phases_period_and_parameters(x);
  
  integration_opt = odeset(...
    'AbsTol',      contopts.multipliers_abs_tol,    ...
    'RelTol',      contopts.multipliers_rel_tol     ...
  );
  if ~ isempty(cds.jacobian_ode)
    integration_opt = odeset(integration_opt, ...
          'Jacobian',     @(t,y) feval(cds.jacobian_ode,t,y,parameters{:}));
  end
  
  if ~ cds.using_cvode
    cds.cycle_orbit = cds.integrator(...
         @(t, y) cds.dydt_ode(t, y, parameters{:}), ...
         [0 period], ...
         phases(:,1), ...
         integration_opt);
  end
 
  cds.phases_0 = x(1:end-2);
  
  monodromy_map = @(x) NewtonPicard.SingleShooting.monodromy_map( ...
                        x, period, parameters, ...
                        contopts.multipliers_abs_tol, ...
                        contopts.multipliers_rel_tol);
  
  nMults_to_compute = min(nMults_to_compute, length(x));
                      
  [~, multiplier_matrix, no_convergence] = eigs(monodromy_map, cds.n_phases, ...
                                                nMults_to_compute);
                                              %'largestabs', ... 
                                              %'Tolerance', 1e-12);
  multipliers = diag(multiplier_matrix);
  
  if no_convergence
    print_diag(0, 'multipliers did not converge\n');
    return
  end
  
  print_diag(1, multipliers2str(multipliers));
end