// this file was generated by the system file generator of cl_matcontL

// this mex function computes the Jacobian matrix of system of ODEs called
//                       "fusion_N_50_cvode_max_ord_1"

#include <math.h>
#include "mex.h"

#define n_parameters 3
#define n_inputs     5
#define n_outputs    1
#define system_size  147

#define input_t 0
#define input_y 1
#define checks false

void fusion_N_50_cvode_max_ord_1_jacobian_params(double* y, double* parameters, double* dydt);

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {

  double parameters[n_parameters];  
  double *y;                      /* 1xN input matrix */
  size_t ncols;                   /* size of matrix */
  double *outMatrix;              /* output matrix */

  /* check for proper number of arguments */
  if(nrhs != n_inputs) {
    mexErrMsgIdAndTxt("fusion_N_50_cvode_max_ord_1_dydt:nrhs","Five inputs required.");
  }
  if(nlhs != n_outputs) {
    mexErrMsgIdAndTxt("fusion_N_50_cvode_max_ord_1_dydt:nlhs","One output required.");
  }


  if ( !mxIsDouble(prhs[input_y]) ) {
    mexErrMsgIdAndTxt("system_fusion_N_50_cvode_max_ord_1:not_double",
                      "Error: Input vector y is not a double.");
  }

  if ( mxGetNumberOfElements(prhs[input_y]) != system_size ) {
    mexErrMsgIdAndTxt("system_fusion_N_50_cvode_max_ord_1:wrong_size",
                     "Input vector y must have 147 elements.");
  }

  for ( int i = 0; i < n_parameters; i++ ) {
    if ( !mxIsDouble(prhs[i + 2]) ) {
      mexErrMsgIdAndTxt("fusion_N_50_cvode_max_ord_1_dydt:not_double",
                        "Error: one of the parameters is not a double");
    } else if ( mxIsComplex(prhs[i + 2]) ) {
      mexErrMsgIdAndTxt("fusion_N_50_cvode_max_ord_1_dydt:not_complex",
                        "Error: one of the parameters not a real number");
    } else if ( mxGetNumberOfElements(prhs[i + 2]) != 1 ) {
      mexErrMsgIdAndTxt("fusion_N_50_cvode_max_ord_1_dydt:notScalar",
                        "Error: one of the parameters is not scalar");
    } else {
      parameters[i] = mxGetScalar(prhs[i+2]);
    }
  }
    
    
  /* create a pointer to the real data in the input matrix  */
  #if MX_HAS_INTERLEAVED_COMPLEX
  y = mxGetDoubles(prhs[input_y]);
  #else
  y = mxGetPr(prhs[input_y]);
  #endif

  /* get dimensions of the input matrix */

  /* create the output matrix */
  plhs[0] = mxCreateDoubleMatrix(system_size, n_parameters, mxREAL);

  /* get a pointer to the real data in the output matrix */
  #if MX_HAS_INTERLEAVED_COMPLEX
  outMatrix = mxGetDoubles(plhs[0]);
  #else
  outMatrix = mxGetPr(plhs[0]);
  #endif

  /* call the computational routine */
  fusion_N_50_cvode_max_ord_1_jacobian_params(y,parameters,outMatrix);
    
}

void fusion_N_50_cvode_max_ord_1_jacobian_params(double* y, double* parameters, double* jac) {
  jac[2] =  2.0E+1;
  jac[5] =  2.0E+1;
  jac[8] =  2.0E+1;
  jac[11] =  2.0E+1;
  jac[14] =  2.0E+1;
  jac[17] =  2.0E+1;
  jac[20] =  2.0E+1;
  jac[23] =  2.0E+1;
  jac[26] =  2.0E+1;
  jac[29] =  2.0E+1;
  jac[32] =  2.0E+1;
  jac[35] =  2.0E+1;
  jac[38] =  2.0E+1;
  jac[41] =  2.0E+1;
  jac[44] =  2.0E+1;
  jac[47] =  2.0E+1;
  jac[50] =  2.0E+1;
  jac[53] =  2.0E+1;
  jac[56] =  2.0E+1;
  jac[59] =  2.0E+1;
  jac[62] =  2.0E+1;
  jac[65] =  2.0E+1;
  jac[68] =  2.0E+1;
  jac[71] =  2.0E+1;
  jac[74] =  2.0E+1;
  jac[77] =  2.0E+1;
  jac[80] =  2.0E+1;
  jac[83] =  2.0E+1;
  jac[86] =  2.0E+1;
  jac[89] =  2.0E+1;
  jac[92] =  2.0E+1;
  jac[95] =  2.0E+1;
  jac[98] =  2.0E+1;
  jac[101] =  2.0E+1;
  jac[104] =  2.0E+1;
  jac[107] =  2.0E+1;
  jac[110] =  2.0E+1;
  jac[113] =  2.0E+1;
  jac[116] =  2.0E+1;
  jac[119] =  2.0E+1;
  jac[122] =  2.0E+1;
  jac[125] =  2.0E+1;
  jac[128] =  2.0E+1;
  jac[131] =  2.0E+1;
  jac[134] =  2.0E+1;
  jac[137] =  2.0E+1;
  jac[140] =  2.0E+1;
  jac[143] =  2.0E+1;
  jac[146] =  2.0E+1;
  jac[149] =  y[2]*-2.0E+1;
  jac[152] =  y[5]*-2.0E+1;
  jac[155] =  y[8]*-2.0E+1;
  jac[158] =  y[11]*-2.0E+1;
  jac[161] =  y[14]*-2.0E+1;
  jac[164] =  y[17]*-2.0E+1;
  jac[167] =  y[20]*-2.0E+1;
  jac[170] =  y[23]*-2.0E+1;
  jac[173] =  y[26]*-2.0E+1;
  jac[176] =  y[29]*-2.0E+1;
  jac[179] =  y[32]*-2.0E+1;
  jac[182] =  y[35]*-2.0E+1;
  jac[185] =  y[38]*-2.0E+1;
  jac[188] =  y[41]*-2.0E+1;
  jac[191] =  y[44]*-2.0E+1;
  jac[194] =  y[47]*-2.0E+1;
  jac[197] =  y[50]*-2.0E+1;
  jac[200] =  y[53]*-2.0E+1;
  jac[203] =  y[56]*-2.0E+1;
  jac[206] =  y[59]*-2.0E+1;
  jac[209] =  y[62]*-2.0E+1;
  jac[212] =  y[65]*-2.0E+1;
  jac[215] =  y[68]*-2.0E+1;
  jac[218] =  y[71]*-2.0E+1;
  jac[221] =  y[74]*-2.0E+1;
  jac[224] =  y[77]*-2.0E+1;
  jac[227] =  y[80]*-2.0E+1;
  jac[230] =  y[83]*-2.0E+1;
  jac[233] =  y[86]*-2.0E+1;
  jac[236] =  y[89]*-2.0E+1;
  jac[239] =  y[92]*-2.0E+1;
  jac[242] =  y[95]*-2.0E+1;
  jac[245] =  y[98]*-2.0E+1;
  jac[248] =  y[101]*-2.0E+1;
  jac[251] =  y[104]*-2.0E+1;
  jac[254] =  y[107]*-2.0E+1;
  jac[257] =  y[110]*-2.0E+1;
  jac[260] =  y[113]*-2.0E+1;
  jac[263] =  y[116]*-2.0E+1;
  jac[266] =  y[119]*-2.0E+1;
  jac[269] =  y[122]*-2.0E+1;
  jac[272] =  y[125]*-2.0E+1;
  jac[275] =  y[128]*-2.0E+1;
  jac[278] =  y[131]*-2.0E+1;
  jac[281] =  y[134]*-2.0E+1;
  jac[284] =  y[137]*-2.0E+1;
  jac[287] =  y[140]*-2.0E+1;
  jac[290] =  y[143]*-2.0E+1;
  jac[293] =  y[146]*-2.0E+1;
  jac[439] =  (((tanh(y[146])*1.499999999925-2.590909090779545)*(y[141]*(-1.180898738998301)+y[144]*1.180898738998301+3.855241794890195E+15/(tanh(y[143]*3.519114426231061E-1-y[146]*1.351911442623106)*1.590287240392205E+16+2.746859778859264E+16))+y[144]*(pow(tanh(y[146]),2.0)*1.499999999925-1.499999999925)*(y[143]*1.180898738998301-y[146]*1.180898738998301))*1.697663294567963E+32)/(y[141]*-4.643638217160084E+32+y[144]*1.783911200609675E+33-y[141]*tanh(y[143]*3.519114426231061E-1-y[146]*1.351911442623106)*2.68842212572426E+32+y[144]*tanh(y[143]*3.519114426231061E-1-y[146]*1.351911442623106)*1.032790695089812E+33+4.543259751445138E+32)+(y[144]*(tanh(y[146])*1.499999999925-2.590909090779545)*5.851781751017811E+32)/(y[141]*-4.643638217160084E+32+y[144]*1.783911200609675E+33-y[141]*tanh(y[143]*3.519114426231061E-1-y[146]*1.351911442623106)*2.68842212572426E+32+y[144]*tanh(y[143]*3.519114426231061E-1-y[146]*1.351911442623106)*1.032790695089812E+33+4.543259751445138E+32)+((tanh(y[146])*(1.1E+1/1.0E+1)-1.9E+1/1.0E+1)*(y[141]*(-1.180898738998301)+y[144]*1.180898738998301+3.855241794890195E+15/(tanh(y[143]*3.519114426231061E-1-y[146]*1.351911442623106)*1.590287240392205E+16+2.746859778859264E+16))*2.54649494172462E+32)/(y[141]*-4.643638217160084E+32+y[144]*1.783911200609675E+33-y[141]*tanh(y[143]*3.519114426231061E-1-y[146]*1.351911442623106)*2.68842212572426E+32+y[144]*tanh(y[143]*3.519114426231061E-1-y[146]*1.351911442623106)*1.032790695089812E+33+4.543259751445138E+32);
  jac[440] =  (-3.055793930222334E+33)/(y[144]*(y[141]*-4.643638217160084E+32+y[144]*1.783911200609675E+33-y[141]*tanh(y[143]*3.519114426231061E-1-y[146]*1.351911442623106)*2.68842212572426E+32+y[144]*tanh(y[143]*3.519114426231061E-1-y[146]*1.351911442623106)*1.032790695089812E+33+4.543259751445138E+32));
}