function recompile_cvode_mex()
 path        = System_of_ODEs.get_cl_matcontL_path;
cvodes_path = fullfile(path, 'SystemFileGenerator', 'cvodes');
dirname     = '+fusion_N_25_cvode';
mex( ... 
  fullfile(path, 'SystemFileGenerator', 'templates', 'cvode_mex.c'), ... 
  fullfile(path, 'Systems', dirname, 'dydt_cvode.c'), ... 
  fullfile(path, 'Systems', dirname, 'jacobian_cvode.c'), ... 
  fullfile(path, 'Systems', dirname, 'd_sensitivity_dt.c'), ... 
  ['-I' fullfile(path, 'SystemFileGenerator', 'cvodes', 'include')], ... 
  ['-I' fullfile(path, 'Systems', dirname)], ... 
  fullfile(cvodes_path, '/arkode/arkode.c'), ... 
  fullfile(cvodes_path, '/arkode/arkode_adapt.c'), ... 
  fullfile(cvodes_path, '/arkode/arkode_arkstep.c'), ... 
  fullfile(cvodes_path, '/arkode/arkode_arkstep_io.c'), ... 
  fullfile(cvodes_path, '/arkode/arkode_arkstep_nls.c'), ... 
  fullfile(cvodes_path, '/arkode/arkode_bandpre.c'), ... 
  fullfile(cvodes_path, '/arkode/arkode_bbdpre.c'), ... 
  fullfile(cvodes_path, '/arkode/arkode_butcher.c'), ... 
  fullfile(cvodes_path, '/arkode/arkode_butcher_dirk.c'), ... 
  fullfile(cvodes_path, '/arkode/arkode_butcher_erk.c'), ... 
  fullfile(cvodes_path, '/arkode/arkode_erkstep.c'), ... 
  fullfile(cvodes_path, '/arkode/arkode_erkstep_io.c'), ... 
  fullfile(cvodes_path, '/arkode/arkode_interp.c'), ... 
  fullfile(cvodes_path, '/arkode/arkode_io.c'), ... 
  fullfile(cvodes_path, '/arkode/arkode_ls.c'), ... 
  fullfile(cvodes_path, '/arkode/arkode_mristep.c'), ... 
  fullfile(cvodes_path, '/arkode/arkode_mristep_io.c'), ... 
  fullfile(cvodes_path, '/arkode/arkode_root.c'), ... 
  fullfile(cvodes_path, '/cvodes/cvodea.c'), ... 
  fullfile(cvodes_path, '/cvodes/cvodea_io.c'), ... 
  fullfile(cvodes_path, '/cvodes/cvodes.c'), ... 
  fullfile(cvodes_path, '/cvodes/cvodes_bandpre.c'), ... 
  fullfile(cvodes_path, '/cvodes/cvodes_bbdpre.c'), ... 
  fullfile(cvodes_path, '/cvodes/cvodes_diag.c'), ... 
  fullfile(cvodes_path, '/cvodes/cvodes_direct.c'), ... 
  fullfile(cvodes_path, '/cvodes/cvodes_io.c'), ... 
  fullfile(cvodes_path, '/cvodes/cvodes_ls.c'), ... 
  fullfile(cvodes_path, '/cvodes/cvodes_nls.c'), ... 
  fullfile(cvodes_path, '/cvodes/cvodes_nls_sim.c'), ... 
  fullfile(cvodes_path, '/cvodes/cvodes_nls_stg.c'), ... 
  fullfile(cvodes_path, '/cvodes/cvodes_nls_stg1.c'), ... 
  fullfile(cvodes_path, '/cvodes/cvodes_spils.c'), ... 
  fullfile(cvodes_path, '/nvector/serial/fnvector_serial.c'), ... 
  fullfile(cvodes_path, '/nvector/serial/nvector_serial.c'), ... 
  fullfile(cvodes_path, '/sundials/sundials_band.c'), ... 
  fullfile(cvodes_path, '/sundials/sundials_dense.c'), ... 
  fullfile(cvodes_path, '/sundials/sundials_direct.c'), ... 
  fullfile(cvodes_path, '/sundials/sundials_iterative.c'), ... 
  fullfile(cvodes_path, '/sundials/sundials_linearsolver.c'), ... 
  fullfile(cvodes_path, '/sundials/sundials_math.c'), ... 
  fullfile(cvodes_path, '/sundials/sundials_matrix.c'), ... 
  fullfile(cvodes_path, '/sundials/sundials_nonlinearsolver.c'), ... 
  fullfile(cvodes_path, '/sundials/sundials_nvector.c'), ... 
  fullfile(cvodes_path, '/sundials/sundials_nvector_senswrapper.c'), ... 
  fullfile(cvodes_path, '/sundials/sundials_version.c'), ... 
  fullfile(cvodes_path, '/sunlinsol/band/fsunlinsol_band.c'), ... 
  fullfile(cvodes_path, '/sunlinsol/band/sunlinsol_band.c'), ... 
  fullfile(cvodes_path, '/sunlinsol/dense/fsunlinsol_dense.c'), ... 
  fullfile(cvodes_path, '/sunlinsol/dense/sunlinsol_dense.c'), ... 
  fullfile(cvodes_path, '/sunmatrix/band/fsunmatrix_band.c'), ... 
  fullfile(cvodes_path, '/sunmatrix/band/sunmatrix_band.c'), ... 
  fullfile(cvodes_path, '/sunmatrix/dense/fsunmatrix_dense.c'), ... 
  fullfile(cvodes_path, '/sunmatrix/dense/sunmatrix_dense.c'), ... 
  fullfile(cvodes_path, '/sunmatrix/sparse/fsunmatrix_sparse.c'), ... 
  fullfile(cvodes_path, '/sunmatrix/sparse/sunmatrix_sparse.c'), ... 
  fullfile(cvodes_path, '/sunnonlinsol/fixedpoint/fsunnonlinsol_fixedpoint.c'), ... 
  fullfile(cvodes_path, '/sunnonlinsol/fixedpoint/sunnonlinsol_fixedpoint.c'), ... 
  fullfile(cvodes_path, '/sunnonlinsol/newton/fsunnonlinsol_newton.c'), ... 
  fullfile(cvodes_path, '/sunnonlinsol/newton/sunnonlinsol_newton.c'), ... 
  '-output', ... 
  fullfile(path, 'Systems', dirname, 'cvode') ... 
)
 end