function extend_fusion_cycles
  N = 25;                     
  odefile = str2func(sprintf('fusion_N_%d', N));

  subdirectory              = 'fusion_cycles';
  dirname                   = fullfile(get_path(), 'Data', subdirectory);
  [point_file, point_index] = get_latest_point_file(dirname);


  load(point_file, 'point');

  init_collocation_extend_curve( ...
    'continuation_state',           point.x, ...
    'odefile',                      odefile,  ...
    'ode_parameters',               point.parametervalues, ...
    'active_parameter_index',       3, ...
    'time_mesh',                    point.timemesh, ...
    'current_n_mesh_intervals',     point.ntst, ...
    'current_nCollocationPoints',   point.ncol ...
  );

  opt = contset( ...
    'MaxNumPoints',            point_index + 12, ...
    'InitStepsize',            0.25, ...
    'MinStepsize',             1e-6, ...
    'MaxStepsize',             0.25, ...
    'MaxNewtonIters',          8, ...
    'VarTolerance',            1e-8, ...
    'FunTolerance',            1e-8, ...
    'Multipliers',             true, ...
    'Singularities',           true, ...
    'MoorePenrose',            false, ...
    'contL_SmoothingAngle',    1, ...
    'newtcorrL_use_max_norm',  true, ...
    'enable_nf_pd',            false, ...
    'enable_nf_lpc',           true, ...
    'enable_nf_ns',            false, ...
    'initial_point_index',     point_index, ...
    'Filename',                subdirectory, ...
    'set_direction',           false, ...
    'singularity_callback',    @plot_singularity_of_cycles);

  figure
  hold on
  title('fusion - extenstion of continuation');
  xlabel('q_{inf}')
  ylabel('period')


  contL(@limitcycleL, point.x, point.v, opt,'callback', @plot_T_versus_param);
end