% continuation of cycles in fusion system.
clc
clear global
N = 25;                     
odefile = str2func(sprintf('fusion_precomputed_with_sage_N_%d', N));
a = -1;
b = -0.3;  
q_inf = -0.72;

ode_parameters = {a ; b; q_inf};


initial_continuation_data = init_collocation_find_stable_cycle( ...
  'initial_point',             ones(3*(N-1),1), ...
  'time_to_converge_to_cycle', 150, ... 
  'odefile',                   odefile,  ...
  'ode_parameters',            ode_parameters, ...
  'active_parameter_index',    3, ...
  'lower_bound_period',        1, ...
  'upper_bound_period',        10, ...
  'nMeshIntervals',            40, ...
  'poincare_tolerance',        1e-1, ...
  'show_plots',                false ...
);

options = contset( ...
  'MaxNumPoints',            70, ...
  'InitStepsize',            0.25, ...
  'MinStepsize',             1e-6, ...
  'MaxStepsize',             0.25, ...
  'MaxNewtonIters',          8, ...
  'MaxCorrIters',            10, ...
  'MaxTestIters',            10, ...
  'Backward',                false, ...
  'VarTolerance',            1e-3, ...
  'FunTolerance',            1e-3, ...
  'Adapt',                   3, ...
  'Multipliers',             true, ...
  'Singularities',           true, ...
  'MoorePenrose',            false, ...
  'contL_SmoothingAngle',    1, ...
  'enable_nf_pd',            false, ...
  'enable_nf_lpc',           true, ...
  'enable_nf_ns',            false, ...
  'Filename',                mfilename);

contL(@limitcycleL, initial_continuation_data, [], options, ...
                   'callback', @plot_T_versus_param);