// this file was generated by the system file generator of cl_matcontL

// this mex function computes the right hand side of system of ODEs called
//                       "sei"

#include <math.h>
#include "mex.h"

#define n_parameters 5
#define n_inputs     7
#define system_size  5

#define input_t 0
#define input_y 1


void sei_dydt(double* y, double* parameters, double* dydt);

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {

  double parameters[n_parameters];  
  double *y;                      /* 1xN input matrix */
  size_t ncols;                   /* size of matrix */
  double *outMatrix;              /* output matrix */

  /* check for proper number of arguments */
  if(nrhs != n_inputs) {
    mexErrMsgIdAndTxt("sei_dydt:nrhs","%d inputs required.", n_inputs);
  }

  if ( !mxIsDouble(prhs[input_y]) ) {
    mexErrMsgIdAndTxt("system_sei:not_double",
                      "Error: Input vector y is not a double.");
  }

  if ( mxGetNumberOfElements(prhs[input_y]) != system_size ) {
    mexErrMsgIdAndTxt("system_sei:wrong_size",
                     "Input vector y must have 5 elements.");
  }

  for ( int i = 0; i < n_parameters; i++ ) {
    if ( !mxIsDouble(prhs[i + 2]) ) {
      mexErrMsgIdAndTxt("sei_dydt:not_double",
                        "Error: one of the parameters is not a double");
    } else if ( mxIsComplex(prhs[i + 2]) ) {
      mexErrMsgIdAndTxt("sei_dydt:not_complex",
                        "Error: one of the parameters not a real number");
    } else if ( mxGetNumberOfElements(prhs[i + 2]) != 1 ) {
      mexErrMsgIdAndTxt("sei_dydt:notScalar",
                        "Error: one of the parameters is not scalar");
    } else {
      parameters[i] = mxGetScalar(prhs[i+2]);
    }
  }
    
    
  /* create a pointer to the real data in the input matrix  */
  #if MX_HAS_INTERLEAVED_COMPLEX
  y = mxGetDoubles(prhs[input_y]);
  #else
  y = mxGetPr(prhs[input_y]);
  #endif

  /* get dimensions of the input matrix */

  /* create the output matrix */
  plhs[0] = mxCreateDoubleMatrix(system_size, 1, mxREAL);

  /* get a pointer to the real data in the output matrix */
  #if MX_HAS_INTERLEAVED_COMPLEX
  outMatrix = mxGetDoubles(plhs[0]);
  #else
  outMatrix = mxGetPr(plhs[0]);
  #endif

  /* call the computational routine */
  sei_dydt(y,parameters,outMatrix);
    
}

void sei_dydt(double* y, double* parameters, double* dydt) {
  dydt[0] =  -parameters[2]+parameters[2]*exp(-y[0])-parameters[1]*exp(y[2])*(parameters[3]*y[3]+1.0);
  dydt[1] =  -parameters[0]-parameters[2]+parameters[1]*exp(-y[1]+y[2]+y[0])*(parameters[3]*y[3]+1.0);
  dydt[2] =  -parameters[4]-parameters[2]+parameters[0]*exp(y[1]-y[2]);
  dydt[3] =  y[3]-y[4]*3.141592653589793*2.0-y[3]*(y[3]*y[3]+y[4]*y[4]);
  dydt[4] =  y[4]+y[3]*3.141592653589793*2.0-y[4]*(y[3]*y[3]+y[4]*y[4]);
}