// this file was generated by the system file generator of cl_matcontL

// this mex function computes the right hand side of system of ODEs called
//                       "sei"

#include <math.h>
#include "mex.h"
#include "mex_utils.c"

#define N_PARAMETERS        5
#define REQUIRED_N_INPUTS   7
#define SYSTEM_SIZE         5

#define INPUT_T 0
#define INPUT_Y 1

void mexFunction(int n_outputs,       mxArray *outputs[], 
                 int n_inputs , const mxArray *inputs []) {

  check_n_inputs(n_inputs, REQUIRED_N_INPUTS, "dydt_mex");

  double *y = get_doubles(inputs[INPUT_Y], "Input vector y", SYSTEM_SIZE);

  double parameters[N_PARAMETERS];  
  get_parameters(inputs, parameters, N_PARAMETERS);

  outputs[0] = mxCreateDoubleMatrix(SYSTEM_SIZE, 1, mxREAL);
  double* dydt = my_mex_get_doubles(outputs[0]);

  dydt[0] =  -parameters[2]+parameters[2]*exp(-y[0])-parameters[1]*exp(y[2])*(parameters[3]*y[3]+1.0);
  dydt[1] =  -parameters[0]-parameters[2]+parameters[1]*exp(-y[1]+y[2]+y[0])*(parameters[3]*y[3]+1.0);
  dydt[2] =  -parameters[4]-parameters[2]+parameters[0]*exp(y[1]-y[2]);
  dydt[3] =  y[3]-y[4]*3.141592653589793*2.0-y[3]*(y[3]*y[3]+y[4]*y[4]);
  dydt[4] =  y[4]+y[3]*3.141592653589793*2.0-y[4]*(y[3]*y[3]+y[4]*y[4]);
}