// this file was generated by the system file generator of cl_matcontL

// this mex function computes the Jacobian matrix of system of ODEs called
//                       "sei"

#include <math.h>
#include "mex.h"
#include "mex_utils.c"

#define N_PARAMETERS        5
#define REQUIRED_N_INPUTS   7
#define SYSTEM_SIZE         5

#define INPUT_T 0
#define INPUT_Y 1
#define JAC(i,j) jac[(i) + (j) * SYSTEM_SIZE]

void mexFunction(int n_outputs,       mxArray *outputs[], 
                 int n_inputs , const mxArray *inputs []) {

  check_n_inputs(n_inputs, REQUIRED_N_INPUTS, "jacobian_mex");

  double *y = get_doubles(inputs[INPUT_Y], "Input vector y", SYSTEM_SIZE);

  double parameters[N_PARAMETERS];  
  get_parameters(inputs, parameters, N_PARAMETERS);
    
  outputs[0] = mxCreateDoubleMatrix(SYSTEM_SIZE, SYSTEM_SIZE, mxREAL);
  double* jac = my_mex_get_doubles(outputs[0]);

  JAC(0,0) =  -parameters[2]*exp(-y[0]);
  JAC(1,0) =  parameters[1]*exp(-y[1]+y[2]+y[0])*(parameters[3]*y[3]+1.0);
  JAC(1,1) =  -parameters[1]*exp(-y[1]+y[2]+y[0])*(parameters[3]*y[3]+1.0);
  JAC(2,1) =  parameters[0]*exp(y[1]-y[2]);
  JAC(0,2) =  -parameters[1]*exp(y[2])*(parameters[3]*y[3]+1.0);
  JAC(1,2) =  parameters[1]*exp(-y[1]+y[2]+y[0])*(parameters[3]*y[3]+1.0);
  JAC(2,2) =  -parameters[0]*exp(y[1]-y[2]);
  JAC(0,3) =  -parameters[1]*parameters[3]*exp(y[2]);
  JAC(1,3) =  parameters[1]*parameters[3]*exp(-y[1]+y[2]+y[0]);
  JAC(3,3) =  (y[3]*y[3])*-3.0-y[4]*y[4]+1.0;
  JAC(4,3) =  3.141592653589793*2.0-y[3]*y[4]*2.0;
  JAC(3,4) =  3.141592653589793*-2.0-y[3]*y[4]*2.0;
  JAC(4,4) =  -y[3]*y[3]-(y[4]*y[4])*3.0+1.0;
}
