function has_period = has_period(curvefile)
  has_period = isequal(curvefile, @single_shooting) || ...
               isequal(curvefile, @multiple_shooting) || ...
               isequal(curvefile, @limitcycleL);