function writemesh(x, ix)

cla;
if size(ix,1) == 4
  patch('Vertices', x', ...
        'Faces', ix', ...
        'FaceColor', 'blue', ...
        'EdgeColor', 'black');
elseif size(ix,1) == 9
  patch('Vertices', x', ...
        'Faces', ix(1:8,:)', ...
        'FaceColor', 'blue', ...
        'EdgeColor', 'black');
else
  error('Unknown ix size');
end
