global cds
cds = [];
path = System_of_ODEs.get_cl_matcontL_path();
addpath(fullfile(path, 'Systems', 'bpros273_cvode'))

subspace_size = 3;


% We specify the options for the cycle continuation.

opts_h_lc = contset(...
  'MaxNumPoints',           10000, ...
  'InitStepsize',           0.02, ...
  'MaxStepsize',            0.1, ...
  'MinStepsize',            10^-6.5, ...
  'contL_SmoothingAngle',   100, ...
  'newtcorrL_use_max_norm', true, ...
  'Singularities',          true, ...
  'enable_nf_ns',           false, ...
  'enable_nf_lpc',          false, ...
  'enable_nf_pd',           false, ...
  'MaxCorrIters',           30, ...
  'contL_DiagnosticsLevel', 5, ...
  'console_output_level',   5, ...
  'FunTolerance',           10^-9, ...
  'VarTolerance',           10^-6, ...
  'integration_abs_tol',    1e-15, ...
  'integration_rel_tol',    1e-15, ...
  'multipliers_abs_tol',    1e-15, ...
  'multipliers_rel_tol',    1e-15, ...
  'NewtonPicard',           true, ...
  'monodromy_by_finite_differences', false);

n_mesh_intervals = 20;
[x0] = init_single_shooting_find_stable_cycle(...
  'time_to_converge_to_cycle',  1500, ...
  'odefile',                    @odefile_mex, ...
  'time_integration_method',    @cvode, ...
  'time_integration_options',   odeset('AbsTol', 1e-15, 'RelTol', 1e-15), ...
  'lower_bound_period',         100, ...
  'upper_bound_period',         1000, ...
  'initial_point',              zeros(273,1), ...
  'plot_transformation',        @log10, ...
  'ode_parameters',             0.048975, ...
  'active_parameter_index',     1, ...
  'show_plots',                 false, ...
  'n_computed_points',          10000, ...
  'interpolation',              'nearest', ...
  'subspace_size',              3);


if usejava('jvm')

  figure
  hold on

  xlabel('par1')
  ylabel('period')
  title('bypass')
end

% We run the cycle continuation:
contL(@single_shooting, x0, [], opts_h_lc);





