% demonstration of how to extend a multiple shooting continuation of a cycle.

% note: the current cl_matcontL implementation (june 2019) of multiple shooting
% is quite slow, and in this example it is unnecessary. It is only necessary if
% the cycle is really unstable. This file is just intended to show how to set up
% a multiple shooting continuation.

load([(get_path(), 'point_cycle_ms.mat'));


init_multiple_shooting_extend_curve( ...
  'initial_continuation_state',             point.x, ...
  'nMeshIntervals',                         point.nMeshIntervals, ...
  'ode_parameters',                         point.parameter_values, ...
  'active_parameter_index',                 2, ...
  'time_mesh',                              point.time_mesh, ...
  'odefile',                                @brusselator_1d,  ...
  'subspace_size',                          length(point.multipliers));


opts = contset( ...
  ...
  'InitStepsize',           0.05, ...
  'MaxStepsize',            0.05, ...
  'MaxNumPoints',           10, ...
  'contL_DiagnosticsLevel', 4, ...
  'console_output_level',   4, ...
  'NewtonPicard',           true, ...
  'contL_SmoothingAngle',   100, ...
  'newtcorrL_use_max_norm', true, ...
  'Singularities',          true, ...
  'enable_nf_ns',           false, ...
  'enable_nf_lpc',          false, ...
  'enable_nf_pd',           false);


singularities = contL(@multiple_shooting, point.x, point.v, opts);



