% demonstration of how to extend a collocation continuation of a cycle.

load(fullfile(get_path(), 'point_cycle_oc.mat'));


L = 0.5; A = 2; B = 5.45; Dx = 0.008; Dy = 0.004;
ode_parameters = {N L A B Dx Dy};


init_collocation_extend_curve( ...
  'continuation_state',                     point.x, ...
  'ode_parameters',                         point.parametervalues, ...
  'active_parameter_index',                 2, ...
  'odefile',                                @brusselator_1d,  ...
  'time_mesh',                              point.timemesh, ...
  'current_nMeshIntervals',                 point.ntst, ...
  'current_nCollocationPoints',             point.ncol);

opts = contset();
opts = contset(opts, ...
  ...
  'InitStepsize',           0.05, ...
  'MaxStepsize',            0.05, ...
  'MaxNumPoints',           10, ...
  'contL_DiagnosticsLevel', 0, ...
  'console_output_level',   0, ...
  'contL_SmoothingAngle',   100, ...
  'newtcorrL_use_max_norm', true, ...
  'Singularities',          true, ...
  'enable_nf_ns',           false, ...
  'enable_nf_lpc',          false, ...
  'enable_nf_pd',           false);

%title_format_string = ...
%  'Brusselator N:%d  A:%.2f  B:%.2f  Dx:%.3f  Dy:%.3f';
%title_format_args = {N,A,B,Dx,Dy};


singularities = contL(@limitcycleL, point.x, point.v, opts);



