% demonstration of how to extend a multiple shooting continuation of a cycle.

% note: the current cl_matcontL implementation (june 2019) of multiple shooting
% with (or without) Newton-Picard is quite slow compared to orthogonal
% collocation for systems of ODEs of up to 350 equations. This file is just
% intended to show how to set up a multiple shooting continuation.

% note: The cycle we will continue here is relatively stable. Therefore, we
% could use single shooting instead of multiple shooting. Single shooting will
% probably always be slightly faster than multiple shooting (regardless of the
% size of the system of ODEs). This file is just intended to show how to set up
% a multiple shooting continuation.

load([get_path(), 'point_cycle_ms.mat']);


init_multiple_shooting_extend_curve( ...
  'initial_continuation_state',             point.x, ...
  'nMeshIntervals',                         point.nMeshIntervals, ...
  'ode_parameters',                         point.parameter_values, ...
  'active_parameter_index',                 2, ...
  'time_mesh',                              point.time_mesh, ...
  'odefile',                                @Brusselator_1d.homogeneous_x0,  ...
  'subspace_size',                          length(point.multipliers));


opts = contset( ...
  ...
  'InitStepsize',           0.05, ...
  'MaxStepsize',            0.05, ...
  'MaxNumPoints',           5, ...
  'contL_DiagnosticsLevel', 4, ...
  'console_output_level',   4, ...
  'NewtonPicard',           true, ...
  'contL_SmoothingAngle',   100, ...
  'newtcorrL_use_max_norm', true, ...
  'Singularities',          true, ...
  'enable_nf_ns',           false, ...
  'enable_nf_lpc',          false, ...
  'enable_nf_pd',           false, ...
  'singularity_callback',   @plot_singularity_of_cycles);


% we open a plot window:
figure
% each line segment of the approximation of the curve is plotted separately
% therefore, the plot has to "hold" the previously plotted line segments
hold on
% we set the axes labels
xlabel('L')
ylabel('period')
title_format_string = 'Brusselator N:%d  A:%.0f  B:%.1f  Dx:%.3f  Dy:%.3f';
title_format_args = {N,A,B,Dx,Dy};
% we set the title of the plot.
% the title has two lines
title({'extended continuation - multiple shooting', ...
       sprintf(title_format_string, title_format_args{:})});

singularities = contL(@multiple_shooting, point.x, point.v, opts, ...
                      'callback', @plot_T_versus_param);



