% demonstration of how to extend a collocation continuation of a cycle.

% We extend the continuation by loading a .mat file with data from a
% continuation point that was saved during a previous contuation of cycles using
% orthogonal collocation. Try running cycle_integration_oc or
% cycle_from_hopf_oc, and loading one .mat files that one of these scripts saved
% in the "Data" subdirectory instead of loading point_cycle_oc.mat.

% Note that we define the demo as a function to facilitate testing of the demo
% during the development of cl_matcontL. (Defining a demo as a function prevents
% demo's from being accidentally dependent on some variable in the workspace.)
% It is perfectly fine to run continuations in cl_matcontL using Matlab scripts
% without defining functions.
function cycle_extend_oc

  load([get_path(), 'point_cycle_oc.mat'], 'point');


  init_collocation_extend_curve( ...
    'continuation_state',                     point.x, ...
    'ode_parameters',                         point.parametervalues, ...
    'active_parameter_index',                 2, ...
    'odefile',                                @Brusselator_1d.homogeneous_x0,  ...
    'time_mesh',                              point.timemesh, ...
    'current_nMeshIntervals',                 point.ntst, ...
    'current_nCollocationPoints',             point.ncol);

  opts = contset();
  opts = contset(opts, ...
    ...
    'InitStepsize',           0.05, ...
    'MaxStepsize',            0.05, ...
    'MaxNumPoints',           30, ...
    'contL_DiagnosticsLevel', 0, ...
    'console_output_level',   0, ...
    'contL_SmoothingAngle',   100, ...
    'newtcorrL_use_max_norm', true, ...
    'Singularities',          true, ...
    'enable_nf_ns',           false, ...
    'enable_nf_lpc',          false, ...
    'enable_nf_pd',           false, ...
    'singularity_callback',   @plot_singularity_of_cycles);

  figure

  % each line segment of the approximation of the curve is plotted separately
  % therefore, the plot has to "hold" the previously plotted line segments
  hold on
  % we set the axes labels
  xlabel('L')
  ylabel('period')
  title_format_string = 'Brusselator N:%d  A:%.0f  B:%.1f  Dx:%.3f  Dy:%.3f';
  % we list all the values of the parameters of the system of ODEs in the title,
  % except the active parameter, which is the second parameter in the array of
  % parameters:
  title_format_args = num2cell(point.parametervalues([1,3,4,5,6]));
  % we set the title of the plot.
  % the title has two lines
  title({'extended continuation - collocation', ...
         sprintf(title_format_string, title_format_args{:})});
  drawnow 
  % we run the cycle continuation:
  contL(@limitcycleL, point.x, point.v, opts, 'callback', @plot_T_versus_param);
end
