// this file was generated by the system file generator of cl_matcontL

// this mex function computes the right hand side of system of ODEs called
//                       "reactor_N_50_cvode_max_ord_1"

#include <math.h>
#include "mex.h"

#define n_parameters 7
#define n_inputs     9
#define n_outputs    1
#define system_size  100

#define input_t 0
#define input_y 1


void reactor_N_50_cvode_max_ord_1_dydt(double* y, double* parameters, double* dydt);

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {

  double parameters[n_parameters];  
  double *y;                      /* 1xN input matrix */
  size_t ncols;                   /* size of matrix */
  double *outMatrix;              /* output matrix */

  /* check for proper number of arguments */
  if(nrhs != n_inputs) {
    mexErrMsgIdAndTxt("reactor_N_50_cvode_max_ord_1_dydt:nrhs","Five inputs required.");
  }
  if(nlhs != n_outputs) {
    mexErrMsgIdAndTxt("reactor_N_50_cvode_max_ord_1_dydt:nlhs","One output required.");
  }


  if ( !mxIsDouble(prhs[input_y]) ) {
    mexErrMsgIdAndTxt("system_reactor_N_50_cvode_max_ord_1:not_double",
                      "Error: Input vector y is not a double.");
  }

  if ( mxGetNumberOfElements(prhs[input_y]) != system_size ) {
    mexErrMsgIdAndTxt("system_reactor_N_50_cvode_max_ord_1:wrong_size",
                     "Input vector y must have 100 elements.");
  }

  for ( int i = 0; i < n_parameters; i++ ) {
    if ( !mxIsDouble(prhs[i + 2]) ) {
      mexErrMsgIdAndTxt("reactor_N_50_cvode_max_ord_1_dydt:not_double",
                        "Error: one of the parameters is not a double");
    } else if ( mxIsComplex(prhs[i + 2]) ) {
      mexErrMsgIdAndTxt("reactor_N_50_cvode_max_ord_1_dydt:not_complex",
                        "Error: one of the parameters not a real number");
    } else if ( mxGetNumberOfElements(prhs[i + 2]) != 1 ) {
      mexErrMsgIdAndTxt("reactor_N_50_cvode_max_ord_1_dydt:notScalar",
                        "Error: one of the parameters is not scalar");
    } else {
      parameters[i] = mxGetScalar(prhs[i+2]);
    }
  }
    
    
  /* create a pointer to the real data in the input matrix  */
  #if MX_HAS_INTERLEAVED_COMPLEX
  y = mxGetDoubles(prhs[input_y]);
  #else
  y = mxGetPr(prhs[input_y]);
  #endif

  /* get dimensions of the input matrix */

  /* create the output matrix */
  plhs[0] = mxCreateDoubleMatrix(system_size, 1, mxREAL);

  /* get a pointer to the real data in the output matrix */
  #if MX_HAS_INTERLEAVED_COMPLEX
  outMatrix = mxGetDoubles(plhs[0]);
  #else
  outMatrix = mxGetPr(plhs[0]);
  #endif

  /* call the computational routine */
  reactor_N_50_cvode_max_ord_1_dydt(y,parameters,outMatrix);
    
}

void reactor_N_50_cvode_max_ord_1_dydt(double* y, double* parameters, double* dydt) {
  dydt[0] =  parameters[1]*(y[0]-1.0)-(y[0]*4.802E+3-y[2]*4.802E+3+parameters[1]*(y[0]-1.0)*9.8E+1)/parameters[1]-parameters[0]*y[0]*exp(-parameters[5]*(1.0/y[1]-1.0));
  dydt[1] =  parameters[3]*(parameters[4]-y[1])+parameters[2]*(y[1]-1.0)-(y[1]*4.802E+3-y[3]*4.802E+3+parameters[2]*(y[1]-1.0)*9.8E+1)/parameters[2]+parameters[6]*parameters[0]*y[0]*exp(-parameters[5]*(1.0/y[1]-1.0));
  dydt[2] =  y[0]*(4.9E+1/2.0)-y[4]*(4.9E+1/2.0)+(y[0]*2.401E+3-y[2]*4.802E+3+y[4]*2.401E+3)/parameters[1]-parameters[0]*y[2]*exp(-parameters[5]*(1.0/y[3]-1.0));
  dydt[3] =  y[1]*(4.9E+1/2.0)-y[5]*(4.9E+1/2.0)+(y[1]*2.401E+3-y[3]*4.802E+3+y[5]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[3])+parameters[6]*parameters[0]*y[2]*exp(-parameters[5]*(1.0/y[3]-1.0));
  dydt[4] =  y[2]*(4.9E+1/2.0)-y[6]*(4.9E+1/2.0)+(y[2]*2.401E+3-y[4]*4.802E+3+y[6]*2.401E+3)/parameters[1]-parameters[0]*y[4]*exp(-parameters[5]*(1.0/y[5]-1.0));
  dydt[5] =  y[3]*(4.9E+1/2.0)-y[7]*(4.9E+1/2.0)+(y[3]*2.401E+3-y[5]*4.802E+3+y[7]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[5])+parameters[6]*parameters[0]*y[4]*exp(-parameters[5]*(1.0/y[5]-1.0));
  dydt[6] =  y[4]*(4.9E+1/2.0)-y[8]*(4.9E+1/2.0)+(y[4]*2.401E+3-y[6]*4.802E+3+y[8]*2.401E+3)/parameters[1]-parameters[0]*y[6]*exp(-parameters[5]*(1.0/y[7]-1.0));
  dydt[7] =  y[5]*(4.9E+1/2.0)-y[9]*(4.9E+1/2.0)+(y[5]*2.401E+3-y[7]*4.802E+3+y[9]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[7])+parameters[6]*parameters[0]*y[6]*exp(-parameters[5]*(1.0/y[7]-1.0));
  dydt[8] =  y[6]*(4.9E+1/2.0)-y[10]*(4.9E+1/2.0)+(y[6]*2.401E+3-y[8]*4.802E+3+y[10]*2.401E+3)/parameters[1]-parameters[0]*y[8]*exp(-parameters[5]*(1.0/y[9]-1.0));
  dydt[9] =  y[7]*(4.9E+1/2.0)-y[11]*(4.9E+1/2.0)+(y[7]*2.401E+3-y[9]*4.802E+3+y[11]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[9])+parameters[6]*parameters[0]*y[8]*exp(-parameters[5]*(1.0/y[9]-1.0));
  dydt[10] =  y[8]*(4.9E+1/2.0)-y[12]*(4.9E+1/2.0)+(y[8]*2.401E+3-y[10]*4.802E+3+y[12]*2.401E+3)/parameters[1]-parameters[0]*y[10]*exp(-parameters[5]*(1.0/y[11]-1.0));
  dydt[11] =  y[9]*(4.9E+1/2.0)-y[13]*(4.9E+1/2.0)+(y[9]*2.401E+3-y[11]*4.802E+3+y[13]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[11])+parameters[6]*parameters[0]*y[10]*exp(-parameters[5]*(1.0/y[11]-1.0));
  dydt[12] =  y[10]*(4.9E+1/2.0)-y[14]*(4.9E+1/2.0)+(y[10]*2.401E+3-y[12]*4.802E+3+y[14]*2.401E+3)/parameters[1]-parameters[0]*y[12]*exp(-parameters[5]*(1.0/y[13]-1.0));
  dydt[13] =  y[11]*(4.9E+1/2.0)-y[15]*(4.9E+1/2.0)+(y[11]*2.401E+3-y[13]*4.802E+3+y[15]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[13])+parameters[6]*parameters[0]*y[12]*exp(-parameters[5]*(1.0/y[13]-1.0));
  dydt[14] =  y[12]*(4.9E+1/2.0)-y[16]*(4.9E+1/2.0)+(y[12]*2.401E+3-y[14]*4.802E+3+y[16]*2.401E+3)/parameters[1]-parameters[0]*y[14]*exp(-parameters[5]*(1.0/y[15]-1.0));
  dydt[15] =  y[13]*(4.9E+1/2.0)-y[17]*(4.9E+1/2.0)+(y[13]*2.401E+3-y[15]*4.802E+3+y[17]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[15])+parameters[6]*parameters[0]*y[14]*exp(-parameters[5]*(1.0/y[15]-1.0));
  dydt[16] =  y[14]*(4.9E+1/2.0)-y[18]*(4.9E+1/2.0)+(y[14]*2.401E+3-y[16]*4.802E+3+y[18]*2.401E+3)/parameters[1]-parameters[0]*y[16]*exp(-parameters[5]*(1.0/y[17]-1.0));
  dydt[17] =  y[15]*(4.9E+1/2.0)-y[19]*(4.9E+1/2.0)+(y[15]*2.401E+3-y[17]*4.802E+3+y[19]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[17])+parameters[6]*parameters[0]*y[16]*exp(-parameters[5]*(1.0/y[17]-1.0));
  dydt[18] =  y[16]*(4.9E+1/2.0)-y[20]*(4.9E+1/2.0)+(y[16]*2.401E+3-y[18]*4.802E+3+y[20]*2.401E+3)/parameters[1]-parameters[0]*y[18]*exp(-parameters[5]*(1.0/y[19]-1.0));
  dydt[19] =  y[17]*(4.9E+1/2.0)-y[21]*(4.9E+1/2.0)+(y[17]*2.401E+3-y[19]*4.802E+3+y[21]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[19])+parameters[6]*parameters[0]*y[18]*exp(-parameters[5]*(1.0/y[19]-1.0));
  dydt[20] =  y[18]*(4.9E+1/2.0)-y[22]*(4.9E+1/2.0)+(y[18]*2.401E+3-y[20]*4.802E+3+y[22]*2.401E+3)/parameters[1]-parameters[0]*y[20]*exp(-parameters[5]*(1.0/y[21]-1.0));
  dydt[21] =  y[19]*(4.9E+1/2.0)-y[23]*(4.9E+1/2.0)+(y[19]*2.401E+3-y[21]*4.802E+3+y[23]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[21])+parameters[6]*parameters[0]*y[20]*exp(-parameters[5]*(1.0/y[21]-1.0));
  dydt[22] =  y[20]*(4.9E+1/2.0)-y[24]*(4.9E+1/2.0)+(y[20]*2.401E+3-y[22]*4.802E+3+y[24]*2.401E+3)/parameters[1]-parameters[0]*y[22]*exp(-parameters[5]*(1.0/y[23]-1.0));
  dydt[23] =  y[21]*(4.9E+1/2.0)-y[25]*(4.9E+1/2.0)+(y[21]*2.401E+3-y[23]*4.802E+3+y[25]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[23])+parameters[6]*parameters[0]*y[22]*exp(-parameters[5]*(1.0/y[23]-1.0));
  dydt[24] =  y[22]*(4.9E+1/2.0)-y[26]*(4.9E+1/2.0)+(y[22]*2.401E+3-y[24]*4.802E+3+y[26]*2.401E+3)/parameters[1]-parameters[0]*y[24]*exp(-parameters[5]*(1.0/y[25]-1.0));
  dydt[25] =  y[23]*(4.9E+1/2.0)-y[27]*(4.9E+1/2.0)+(y[23]*2.401E+3-y[25]*4.802E+3+y[27]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[25])+parameters[6]*parameters[0]*y[24]*exp(-parameters[5]*(1.0/y[25]-1.0));
  dydt[26] =  y[24]*(4.9E+1/2.0)-y[28]*(4.9E+1/2.0)+(y[24]*2.401E+3-y[26]*4.802E+3+y[28]*2.401E+3)/parameters[1]-parameters[0]*y[26]*exp(-parameters[5]*(1.0/y[27]-1.0));
  dydt[27] =  y[25]*(4.9E+1/2.0)-y[29]*(4.9E+1/2.0)+(y[25]*2.401E+3-y[27]*4.802E+3+y[29]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[27])+parameters[6]*parameters[0]*y[26]*exp(-parameters[5]*(1.0/y[27]-1.0));
  dydt[28] =  y[26]*(4.9E+1/2.0)-y[30]*(4.9E+1/2.0)+(y[26]*2.401E+3-y[28]*4.802E+3+y[30]*2.401E+3)/parameters[1]-parameters[0]*y[28]*exp(-parameters[5]*(1.0/y[29]-1.0));
  dydt[29] =  y[27]*(4.9E+1/2.0)-y[31]*(4.9E+1/2.0)+(y[27]*2.401E+3-y[29]*4.802E+3+y[31]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[29])+parameters[6]*parameters[0]*y[28]*exp(-parameters[5]*(1.0/y[29]-1.0));
  dydt[30] =  y[28]*(4.9E+1/2.0)-y[32]*(4.9E+1/2.0)+(y[28]*2.401E+3-y[30]*4.802E+3+y[32]*2.401E+3)/parameters[1]-parameters[0]*y[30]*exp(-parameters[5]*(1.0/y[31]-1.0));
  dydt[31] =  y[29]*(4.9E+1/2.0)-y[33]*(4.9E+1/2.0)+(y[29]*2.401E+3-y[31]*4.802E+3+y[33]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[31])+parameters[6]*parameters[0]*y[30]*exp(-parameters[5]*(1.0/y[31]-1.0));
  dydt[32] =  y[30]*(4.9E+1/2.0)-y[34]*(4.9E+1/2.0)+(y[30]*2.401E+3-y[32]*4.802E+3+y[34]*2.401E+3)/parameters[1]-parameters[0]*y[32]*exp(-parameters[5]*(1.0/y[33]-1.0));
  dydt[33] =  y[31]*(4.9E+1/2.0)-y[35]*(4.9E+1/2.0)+(y[31]*2.401E+3-y[33]*4.802E+3+y[35]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[33])+parameters[6]*parameters[0]*y[32]*exp(-parameters[5]*(1.0/y[33]-1.0));
  dydt[34] =  y[32]*(4.9E+1/2.0)-y[36]*(4.9E+1/2.0)+(y[32]*2.401E+3-y[34]*4.802E+3+y[36]*2.401E+3)/parameters[1]-parameters[0]*y[34]*exp(-parameters[5]*(1.0/y[35]-1.0));
  dydt[35] =  y[33]*(4.9E+1/2.0)-y[37]*(4.9E+1/2.0)+(y[33]*2.401E+3-y[35]*4.802E+3+y[37]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[35])+parameters[6]*parameters[0]*y[34]*exp(-parameters[5]*(1.0/y[35]-1.0));
  dydt[36] =  y[34]*(4.9E+1/2.0)-y[38]*(4.9E+1/2.0)+(y[34]*2.401E+3-y[36]*4.802E+3+y[38]*2.401E+3)/parameters[1]-parameters[0]*y[36]*exp(-parameters[5]*(1.0/y[37]-1.0));
  dydt[37] =  y[35]*(4.9E+1/2.0)-y[39]*(4.9E+1/2.0)+(y[35]*2.401E+3-y[37]*4.802E+3+y[39]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[37])+parameters[6]*parameters[0]*y[36]*exp(-parameters[5]*(1.0/y[37]-1.0));
  dydt[38] =  y[36]*(4.9E+1/2.0)-y[40]*(4.9E+1/2.0)+(y[36]*2.401E+3-y[38]*4.802E+3+y[40]*2.401E+3)/parameters[1]-parameters[0]*y[38]*exp(-parameters[5]*(1.0/y[39]-1.0));
  dydt[39] =  y[37]*(4.9E+1/2.0)-y[41]*(4.9E+1/2.0)+(y[37]*2.401E+3-y[39]*4.802E+3+y[41]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[39])+parameters[6]*parameters[0]*y[38]*exp(-parameters[5]*(1.0/y[39]-1.0));
  dydt[40] =  y[38]*(4.9E+1/2.0)-y[42]*(4.9E+1/2.0)+(y[38]*2.401E+3-y[40]*4.802E+3+y[42]*2.401E+3)/parameters[1]-parameters[0]*y[40]*exp(-parameters[5]*(1.0/y[41]-1.0));
  dydt[41] =  y[39]*(4.9E+1/2.0)-y[43]*(4.9E+1/2.0)+(y[39]*2.401E+3-y[41]*4.802E+3+y[43]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[41])+parameters[6]*parameters[0]*y[40]*exp(-parameters[5]*(1.0/y[41]-1.0));
  dydt[42] =  y[40]*(4.9E+1/2.0)-y[44]*(4.9E+1/2.0)+(y[40]*2.401E+3-y[42]*4.802E+3+y[44]*2.401E+3)/parameters[1]-parameters[0]*y[42]*exp(-parameters[5]*(1.0/y[43]-1.0));
  dydt[43] =  y[41]*(4.9E+1/2.0)-y[45]*(4.9E+1/2.0)+(y[41]*2.401E+3-y[43]*4.802E+3+y[45]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[43])+parameters[6]*parameters[0]*y[42]*exp(-parameters[5]*(1.0/y[43]-1.0));
  dydt[44] =  y[42]*(4.9E+1/2.0)-y[46]*(4.9E+1/2.0)+(y[42]*2.401E+3-y[44]*4.802E+3+y[46]*2.401E+3)/parameters[1]-parameters[0]*y[44]*exp(-parameters[5]*(1.0/y[45]-1.0));
  dydt[45] =  y[43]*(4.9E+1/2.0)-y[47]*(4.9E+1/2.0)+(y[43]*2.401E+3-y[45]*4.802E+3+y[47]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[45])+parameters[6]*parameters[0]*y[44]*exp(-parameters[5]*(1.0/y[45]-1.0));
  dydt[46] =  y[44]*(4.9E+1/2.0)-y[48]*(4.9E+1/2.0)+(y[44]*2.401E+3-y[46]*4.802E+3+y[48]*2.401E+3)/parameters[1]-parameters[0]*y[46]*exp(-parameters[5]*(1.0/y[47]-1.0));
  dydt[47] =  y[45]*(4.9E+1/2.0)-y[49]*(4.9E+1/2.0)+(y[45]*2.401E+3-y[47]*4.802E+3+y[49]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[47])+parameters[6]*parameters[0]*y[46]*exp(-parameters[5]*(1.0/y[47]-1.0));
  dydt[48] =  y[46]*(4.9E+1/2.0)-y[50]*(4.9E+1/2.0)+(y[46]*2.401E+3-y[48]*4.802E+3+y[50]*2.401E+3)/parameters[1]-parameters[0]*y[48]*exp(-parameters[5]*(1.0/y[49]-1.0));
  dydt[49] =  y[47]*(4.9E+1/2.0)-y[51]*(4.9E+1/2.0)+(y[47]*2.401E+3-y[49]*4.802E+3+y[51]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[49])+parameters[6]*parameters[0]*y[48]*exp(-parameters[5]*(1.0/y[49]-1.0));
  dydt[50] =  y[48]*(4.9E+1/2.0)-y[52]*(4.9E+1/2.0)+(y[48]*2.401E+3-y[50]*4.802E+3+y[52]*2.401E+3)/parameters[1]-parameters[0]*y[50]*exp(-parameters[5]*(1.0/y[51]-1.0));
  dydt[51] =  y[49]*(4.9E+1/2.0)-y[53]*(4.9E+1/2.0)+(y[49]*2.401E+3-y[51]*4.802E+3+y[53]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[51])+parameters[6]*parameters[0]*y[50]*exp(-parameters[5]*(1.0/y[51]-1.0));
  dydt[52] =  y[50]*(4.9E+1/2.0)-y[54]*(4.9E+1/2.0)+(y[50]*2.401E+3-y[52]*4.802E+3+y[54]*2.401E+3)/parameters[1]-parameters[0]*y[52]*exp(-parameters[5]*(1.0/y[53]-1.0));
  dydt[53] =  y[51]*(4.9E+1/2.0)-y[55]*(4.9E+1/2.0)+(y[51]*2.401E+3-y[53]*4.802E+3+y[55]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[53])+parameters[6]*parameters[0]*y[52]*exp(-parameters[5]*(1.0/y[53]-1.0));
  dydt[54] =  y[52]*(4.9E+1/2.0)-y[56]*(4.9E+1/2.0)+(y[52]*2.401E+3-y[54]*4.802E+3+y[56]*2.401E+3)/parameters[1]-parameters[0]*y[54]*exp(-parameters[5]*(1.0/y[55]-1.0));
  dydt[55] =  y[53]*(4.9E+1/2.0)-y[57]*(4.9E+1/2.0)+(y[53]*2.401E+3-y[55]*4.802E+3+y[57]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[55])+parameters[6]*parameters[0]*y[54]*exp(-parameters[5]*(1.0/y[55]-1.0));
  dydt[56] =  y[54]*(4.9E+1/2.0)-y[58]*(4.9E+1/2.0)+(y[54]*2.401E+3-y[56]*4.802E+3+y[58]*2.401E+3)/parameters[1]-parameters[0]*y[56]*exp(-parameters[5]*(1.0/y[57]-1.0));
  dydt[57] =  y[55]*(4.9E+1/2.0)-y[59]*(4.9E+1/2.0)+(y[55]*2.401E+3-y[57]*4.802E+3+y[59]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[57])+parameters[6]*parameters[0]*y[56]*exp(-parameters[5]*(1.0/y[57]-1.0));
  dydt[58] =  y[56]*(4.9E+1/2.0)-y[60]*(4.9E+1/2.0)+(y[56]*2.401E+3-y[58]*4.802E+3+y[60]*2.401E+3)/parameters[1]-parameters[0]*y[58]*exp(-parameters[5]*(1.0/y[59]-1.0));
  dydt[59] =  y[57]*(4.9E+1/2.0)-y[61]*(4.9E+1/2.0)+(y[57]*2.401E+3-y[59]*4.802E+3+y[61]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[59])+parameters[6]*parameters[0]*y[58]*exp(-parameters[5]*(1.0/y[59]-1.0));
  dydt[60] =  y[58]*(4.9E+1/2.0)-y[62]*(4.9E+1/2.0)+(y[58]*2.401E+3-y[60]*4.802E+3+y[62]*2.401E+3)/parameters[1]-parameters[0]*y[60]*exp(-parameters[5]*(1.0/y[61]-1.0));
  dydt[61] =  y[59]*(4.9E+1/2.0)-y[63]*(4.9E+1/2.0)+(y[59]*2.401E+3-y[61]*4.802E+3+y[63]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[61])+parameters[6]*parameters[0]*y[60]*exp(-parameters[5]*(1.0/y[61]-1.0));
  dydt[62] =  y[60]*(4.9E+1/2.0)-y[64]*(4.9E+1/2.0)+(y[60]*2.401E+3-y[62]*4.802E+3+y[64]*2.401E+3)/parameters[1]-parameters[0]*y[62]*exp(-parameters[5]*(1.0/y[63]-1.0));
  dydt[63] =  y[61]*(4.9E+1/2.0)-y[65]*(4.9E+1/2.0)+(y[61]*2.401E+3-y[63]*4.802E+3+y[65]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[63])+parameters[6]*parameters[0]*y[62]*exp(-parameters[5]*(1.0/y[63]-1.0));
  dydt[64] =  y[62]*(4.9E+1/2.0)-y[66]*(4.9E+1/2.0)+(y[62]*2.401E+3-y[64]*4.802E+3+y[66]*2.401E+3)/parameters[1]-parameters[0]*y[64]*exp(-parameters[5]*(1.0/y[65]-1.0));
  dydt[65] =  y[63]*(4.9E+1/2.0)-y[67]*(4.9E+1/2.0)+(y[63]*2.401E+3-y[65]*4.802E+3+y[67]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[65])+parameters[6]*parameters[0]*y[64]*exp(-parameters[5]*(1.0/y[65]-1.0));
  dydt[66] =  y[64]*(4.9E+1/2.0)-y[68]*(4.9E+1/2.0)+(y[64]*2.401E+3-y[66]*4.802E+3+y[68]*2.401E+3)/parameters[1]-parameters[0]*y[66]*exp(-parameters[5]*(1.0/y[67]-1.0));
  dydt[67] =  y[65]*(4.9E+1/2.0)-y[69]*(4.9E+1/2.0)+(y[65]*2.401E+3-y[67]*4.802E+3+y[69]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[67])+parameters[6]*parameters[0]*y[66]*exp(-parameters[5]*(1.0/y[67]-1.0));
  dydt[68] =  y[66]*(4.9E+1/2.0)-y[70]*(4.9E+1/2.0)+(y[66]*2.401E+3-y[68]*4.802E+3+y[70]*2.401E+3)/parameters[1]-parameters[0]*y[68]*exp(-parameters[5]*(1.0/y[69]-1.0));
  dydt[69] =  y[67]*(4.9E+1/2.0)-y[71]*(4.9E+1/2.0)+(y[67]*2.401E+3-y[69]*4.802E+3+y[71]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[69])+parameters[6]*parameters[0]*y[68]*exp(-parameters[5]*(1.0/y[69]-1.0));
  dydt[70] =  y[68]*(4.9E+1/2.0)-y[72]*(4.9E+1/2.0)+(y[68]*2.401E+3-y[70]*4.802E+3+y[72]*2.401E+3)/parameters[1]-parameters[0]*y[70]*exp(-parameters[5]*(1.0/y[71]-1.0));
  dydt[71] =  y[69]*(4.9E+1/2.0)-y[73]*(4.9E+1/2.0)+(y[69]*2.401E+3-y[71]*4.802E+3+y[73]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[71])+parameters[6]*parameters[0]*y[70]*exp(-parameters[5]*(1.0/y[71]-1.0));
  dydt[72] =  y[70]*(4.9E+1/2.0)-y[74]*(4.9E+1/2.0)+(y[70]*2.401E+3-y[72]*4.802E+3+y[74]*2.401E+3)/parameters[1]-parameters[0]*y[72]*exp(-parameters[5]*(1.0/y[73]-1.0));
  dydt[73] =  y[71]*(4.9E+1/2.0)-y[75]*(4.9E+1/2.0)+(y[71]*2.401E+3-y[73]*4.802E+3+y[75]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[73])+parameters[6]*parameters[0]*y[72]*exp(-parameters[5]*(1.0/y[73]-1.0));
  dydt[74] =  y[72]*(4.9E+1/2.0)-y[76]*(4.9E+1/2.0)+(y[72]*2.401E+3-y[74]*4.802E+3+y[76]*2.401E+3)/parameters[1]-parameters[0]*y[74]*exp(-parameters[5]*(1.0/y[75]-1.0));
  dydt[75] =  y[73]*(4.9E+1/2.0)-y[77]*(4.9E+1/2.0)+(y[73]*2.401E+3-y[75]*4.802E+3+y[77]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[75])+parameters[6]*parameters[0]*y[74]*exp(-parameters[5]*(1.0/y[75]-1.0));
  dydt[76] =  y[74]*(4.9E+1/2.0)-y[78]*(4.9E+1/2.0)+(y[74]*2.401E+3-y[76]*4.802E+3+y[78]*2.401E+3)/parameters[1]-parameters[0]*y[76]*exp(-parameters[5]*(1.0/y[77]-1.0));
  dydt[77] =  y[75]*(4.9E+1/2.0)-y[79]*(4.9E+1/2.0)+(y[75]*2.401E+3-y[77]*4.802E+3+y[79]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[77])+parameters[6]*parameters[0]*y[76]*exp(-parameters[5]*(1.0/y[77]-1.0));
  dydt[78] =  y[76]*(4.9E+1/2.0)-y[80]*(4.9E+1/2.0)+(y[76]*2.401E+3-y[78]*4.802E+3+y[80]*2.401E+3)/parameters[1]-parameters[0]*y[78]*exp(-parameters[5]*(1.0/y[79]-1.0));
  dydt[79] =  y[77]*(4.9E+1/2.0)-y[81]*(4.9E+1/2.0)+(y[77]*2.401E+3-y[79]*4.802E+3+y[81]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[79])+parameters[6]*parameters[0]*y[78]*exp(-parameters[5]*(1.0/y[79]-1.0));
  dydt[80] =  y[78]*(4.9E+1/2.0)-y[82]*(4.9E+1/2.0)+(y[78]*2.401E+3-y[80]*4.802E+3+y[82]*2.401E+3)/parameters[1]-parameters[0]*y[80]*exp(-parameters[5]*(1.0/y[81]-1.0));
  dydt[81] =  y[79]*(4.9E+1/2.0)-y[83]*(4.9E+1/2.0)+(y[79]*2.401E+3-y[81]*4.802E+3+y[83]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[81])+parameters[6]*parameters[0]*y[80]*exp(-parameters[5]*(1.0/y[81]-1.0));
  dydt[82] =  y[80]*(4.9E+1/2.0)-y[84]*(4.9E+1/2.0)+(y[80]*2.401E+3-y[82]*4.802E+3+y[84]*2.401E+3)/parameters[1]-parameters[0]*y[82]*exp(-parameters[5]*(1.0/y[83]-1.0));
  dydt[83] =  y[81]*(4.9E+1/2.0)-y[85]*(4.9E+1/2.0)+(y[81]*2.401E+3-y[83]*4.802E+3+y[85]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[83])+parameters[6]*parameters[0]*y[82]*exp(-parameters[5]*(1.0/y[83]-1.0));
  dydt[84] =  y[82]*(4.9E+1/2.0)-y[86]*(4.9E+1/2.0)+(y[82]*2.401E+3-y[84]*4.802E+3+y[86]*2.401E+3)/parameters[1]-parameters[0]*y[84]*exp(-parameters[5]*(1.0/y[85]-1.0));
  dydt[85] =  y[83]*(4.9E+1/2.0)-y[87]*(4.9E+1/2.0)+(y[83]*2.401E+3-y[85]*4.802E+3+y[87]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[85])+parameters[6]*parameters[0]*y[84]*exp(-parameters[5]*(1.0/y[85]-1.0));
  dydt[86] =  y[84]*(4.9E+1/2.0)-y[88]*(4.9E+1/2.0)+(y[84]*2.401E+3-y[86]*4.802E+3+y[88]*2.401E+3)/parameters[1]-parameters[0]*y[86]*exp(-parameters[5]*(1.0/y[87]-1.0));
  dydt[87] =  y[85]*(4.9E+1/2.0)-y[89]*(4.9E+1/2.0)+(y[85]*2.401E+3-y[87]*4.802E+3+y[89]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[87])+parameters[6]*parameters[0]*y[86]*exp(-parameters[5]*(1.0/y[87]-1.0));
  dydt[88] =  y[86]*(4.9E+1/2.0)-y[90]*(4.9E+1/2.0)+(y[86]*2.401E+3-y[88]*4.802E+3+y[90]*2.401E+3)/parameters[1]-parameters[0]*y[88]*exp(-parameters[5]*(1.0/y[89]-1.0));
  dydt[89] =  y[87]*(4.9E+1/2.0)-y[91]*(4.9E+1/2.0)+(y[87]*2.401E+3-y[89]*4.802E+3+y[91]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[89])+parameters[6]*parameters[0]*y[88]*exp(-parameters[5]*(1.0/y[89]-1.0));
  dydt[90] =  y[88]*(4.9E+1/2.0)-y[92]*(4.9E+1/2.0)+(y[88]*2.401E+3-y[90]*4.802E+3+y[92]*2.401E+3)/parameters[1]-parameters[0]*y[90]*exp(-parameters[5]*(1.0/y[91]-1.0));
  dydt[91] =  y[89]*(4.9E+1/2.0)-y[93]*(4.9E+1/2.0)+(y[89]*2.401E+3-y[91]*4.802E+3+y[93]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[91])+parameters[6]*parameters[0]*y[90]*exp(-parameters[5]*(1.0/y[91]-1.0));
  dydt[92] =  y[90]*(4.9E+1/2.0)-y[94]*(4.9E+1/2.0)+(y[90]*2.401E+3-y[92]*4.802E+3+y[94]*2.401E+3)/parameters[1]-parameters[0]*y[92]*exp(-parameters[5]*(1.0/y[93]-1.0));
  dydt[93] =  y[91]*(4.9E+1/2.0)-y[95]*(4.9E+1/2.0)+(y[91]*2.401E+3-y[93]*4.802E+3+y[95]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[93])+parameters[6]*parameters[0]*y[92]*exp(-parameters[5]*(1.0/y[93]-1.0));
  dydt[94] =  y[92]*(4.9E+1/2.0)-y[96]*(4.9E+1/2.0)+(y[92]*2.401E+3-y[94]*4.802E+3+y[96]*2.401E+3)/parameters[1]-parameters[0]*y[94]*exp(-parameters[5]*(1.0/y[95]-1.0));
  dydt[95] =  y[93]*(4.9E+1/2.0)-y[97]*(4.9E+1/2.0)+(y[93]*2.401E+3-y[95]*4.802E+3+y[97]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[95])+parameters[6]*parameters[0]*y[94]*exp(-parameters[5]*(1.0/y[95]-1.0));
  dydt[96] =  y[94]*(4.9E+1/2.0)-y[98]*(4.9E+1/2.0)+(y[94]*2.401E+3-y[96]*4.802E+3+y[98]*2.401E+3)/parameters[1]-parameters[0]*y[96]*exp(-parameters[5]*(1.0/y[97]-1.0));
  dydt[97] =  y[95]*(4.9E+1/2.0)-y[99]*(4.9E+1/2.0)+(y[95]*2.401E+3-y[97]*4.802E+3+y[99]*2.401E+3)/parameters[2]+parameters[3]*(parameters[4]-y[97])+parameters[6]*parameters[0]*y[96]*exp(-parameters[5]*(1.0/y[97]-1.0));
  dydt[98] =  (y[96]*4.802E+3-y[98]*4.802E+3)/parameters[1]-parameters[0]*y[98]*exp(-parameters[5]*(1.0/y[99]-1.0));
  dydt[99] =  (y[97]*4.802E+3-y[99]*4.802E+3)/parameters[2]+parameters[3]*(parameters[4]-y[99])+parameters[6]*parameters[0]*y[98]*exp(-parameters[5]*(1.0/y[99]-1.0));
}