// this file was generated by the system file generator of cl_matcontL

// this mex function computes the Jacobian matrix of system of ODEs called
//                       "reactor_N_50_cvode_max_ord_1"

#include <math.h>
#include "mex.h"

#define n_parameters 7
#define n_inputs     9
#define n_outputs    1
#define system_size  100

#define input_t 0
#define input_y 1
#define checks false

void reactor_N_50_cvode_max_ord_1_jacobian_params(double* y, double* parameters, double* dydt);

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {

  double parameters[n_parameters];  
  double *y;                      /* 1xN input matrix */
  size_t ncols;                   /* size of matrix */
  double *outMatrix;              /* output matrix */

  /* check for proper number of arguments */
  if(nrhs != n_inputs) {
    mexErrMsgIdAndTxt("reactor_N_50_cvode_max_ord_1_dydt:nrhs","Five inputs required.");
  }
  if(nlhs != n_outputs) {
    mexErrMsgIdAndTxt("reactor_N_50_cvode_max_ord_1_dydt:nlhs","One output required.");
  }


  if ( !mxIsDouble(prhs[input_y]) ) {
    mexErrMsgIdAndTxt("system_reactor_N_50_cvode_max_ord_1:not_double",
                      "Error: Input vector y is not a double.");
  }

  if ( mxGetNumberOfElements(prhs[input_y]) != system_size ) {
    mexErrMsgIdAndTxt("system_reactor_N_50_cvode_max_ord_1:wrong_size",
                     "Input vector y must have 100 elements.");
  }

  for ( int i = 0; i < n_parameters; i++ ) {
    if ( !mxIsDouble(prhs[i + 2]) ) {
      mexErrMsgIdAndTxt("reactor_N_50_cvode_max_ord_1_dydt:not_double",
                        "Error: one of the parameters is not a double");
    } else if ( mxIsComplex(prhs[i + 2]) ) {
      mexErrMsgIdAndTxt("reactor_N_50_cvode_max_ord_1_dydt:not_complex",
                        "Error: one of the parameters not a real number");
    } else if ( mxGetNumberOfElements(prhs[i + 2]) != 1 ) {
      mexErrMsgIdAndTxt("reactor_N_50_cvode_max_ord_1_dydt:notScalar",
                        "Error: one of the parameters is not scalar");
    } else {
      parameters[i] = mxGetScalar(prhs[i+2]);
    }
  }
    
    
  /* create a pointer to the real data in the input matrix  */
  #if MX_HAS_INTERLEAVED_COMPLEX
  y = mxGetDoubles(prhs[input_y]);
  #else
  y = mxGetPr(prhs[input_y]);
  #endif

  /* get dimensions of the input matrix */

  /* create the output matrix */
  plhs[0] = mxCreateDoubleMatrix(system_size, n_parameters, mxREAL);

  /* get a pointer to the real data in the output matrix */
  #if MX_HAS_INTERLEAVED_COMPLEX
  outMatrix = mxGetDoubles(plhs[0]);
  #else
  outMatrix = mxGetPr(plhs[0]);
  #endif

  /* call the computational routine */
  reactor_N_50_cvode_max_ord_1_jacobian_params(y,parameters,outMatrix);
    
}

#define JAC(i,j) jac[(i) + (j) * system_size]

void reactor_N_50_cvode_max_ord_1_jacobian_params(double* y, double* parameters, double* jac) {
  JAC(0,0) =  -y[0]*exp(-parameters[5]*(1.0/y[1]-1.0));
  JAC(1,0) =  parameters[6]*y[0]*exp(-parameters[5]*(1.0/y[1]-1.0));
  JAC(2,0) =  -y[2]*exp(-parameters[5]*(1.0/y[3]-1.0));
  JAC(3,0) =  parameters[6]*y[2]*exp(-parameters[5]*(1.0/y[3]-1.0));
  JAC(4,0) =  -y[4]*exp(-parameters[5]*(1.0/y[5]-1.0));
  JAC(5,0) =  parameters[6]*y[4]*exp(-parameters[5]*(1.0/y[5]-1.0));
  JAC(6,0) =  -y[6]*exp(-parameters[5]*(1.0/y[7]-1.0));
  JAC(7,0) =  parameters[6]*y[6]*exp(-parameters[5]*(1.0/y[7]-1.0));
  JAC(8,0) =  -y[8]*exp(-parameters[5]*(1.0/y[9]-1.0));
  JAC(9,0) =  parameters[6]*y[8]*exp(-parameters[5]*(1.0/y[9]-1.0));
  JAC(10,0) =  -y[10]*exp(-parameters[5]*(1.0/y[11]-1.0));
  JAC(11,0) =  parameters[6]*y[10]*exp(-parameters[5]*(1.0/y[11]-1.0));
  JAC(12,0) =  -y[12]*exp(-parameters[5]*(1.0/y[13]-1.0));
  JAC(13,0) =  parameters[6]*y[12]*exp(-parameters[5]*(1.0/y[13]-1.0));
  JAC(14,0) =  -y[14]*exp(-parameters[5]*(1.0/y[15]-1.0));
  JAC(15,0) =  parameters[6]*y[14]*exp(-parameters[5]*(1.0/y[15]-1.0));
  JAC(16,0) =  -y[16]*exp(-parameters[5]*(1.0/y[17]-1.0));
  JAC(17,0) =  parameters[6]*y[16]*exp(-parameters[5]*(1.0/y[17]-1.0));
  JAC(18,0) =  -y[18]*exp(-parameters[5]*(1.0/y[19]-1.0));
  JAC(19,0) =  parameters[6]*y[18]*exp(-parameters[5]*(1.0/y[19]-1.0));
  JAC(20,0) =  -y[20]*exp(-parameters[5]*(1.0/y[21]-1.0));
  JAC(21,0) =  parameters[6]*y[20]*exp(-parameters[5]*(1.0/y[21]-1.0));
  JAC(22,0) =  -y[22]*exp(-parameters[5]*(1.0/y[23]-1.0));
  JAC(23,0) =  parameters[6]*y[22]*exp(-parameters[5]*(1.0/y[23]-1.0));
  JAC(24,0) =  -y[24]*exp(-parameters[5]*(1.0/y[25]-1.0));
  JAC(25,0) =  parameters[6]*y[24]*exp(-parameters[5]*(1.0/y[25]-1.0));
  JAC(26,0) =  -y[26]*exp(-parameters[5]*(1.0/y[27]-1.0));
  JAC(27,0) =  parameters[6]*y[26]*exp(-parameters[5]*(1.0/y[27]-1.0));
  JAC(28,0) =  -y[28]*exp(-parameters[5]*(1.0/y[29]-1.0));
  JAC(29,0) =  parameters[6]*y[28]*exp(-parameters[5]*(1.0/y[29]-1.0));
  JAC(30,0) =  -y[30]*exp(-parameters[5]*(1.0/y[31]-1.0));
  JAC(31,0) =  parameters[6]*y[30]*exp(-parameters[5]*(1.0/y[31]-1.0));
  JAC(32,0) =  -y[32]*exp(-parameters[5]*(1.0/y[33]-1.0));
  JAC(33,0) =  parameters[6]*y[32]*exp(-parameters[5]*(1.0/y[33]-1.0));
  JAC(34,0) =  -y[34]*exp(-parameters[5]*(1.0/y[35]-1.0));
  JAC(35,0) =  parameters[6]*y[34]*exp(-parameters[5]*(1.0/y[35]-1.0));
  JAC(36,0) =  -y[36]*exp(-parameters[5]*(1.0/y[37]-1.0));
  JAC(37,0) =  parameters[6]*y[36]*exp(-parameters[5]*(1.0/y[37]-1.0));
  JAC(38,0) =  -y[38]*exp(-parameters[5]*(1.0/y[39]-1.0));
  JAC(39,0) =  parameters[6]*y[38]*exp(-parameters[5]*(1.0/y[39]-1.0));
  JAC(40,0) =  -y[40]*exp(-parameters[5]*(1.0/y[41]-1.0));
  JAC(41,0) =  parameters[6]*y[40]*exp(-parameters[5]*(1.0/y[41]-1.0));
  JAC(42,0) =  -y[42]*exp(-parameters[5]*(1.0/y[43]-1.0));
  JAC(43,0) =  parameters[6]*y[42]*exp(-parameters[5]*(1.0/y[43]-1.0));
  JAC(44,0) =  -y[44]*exp(-parameters[5]*(1.0/y[45]-1.0));
  JAC(45,0) =  parameters[6]*y[44]*exp(-parameters[5]*(1.0/y[45]-1.0));
  JAC(46,0) =  -y[46]*exp(-parameters[5]*(1.0/y[47]-1.0));
  JAC(47,0) =  parameters[6]*y[46]*exp(-parameters[5]*(1.0/y[47]-1.0));
  JAC(48,0) =  -y[48]*exp(-parameters[5]*(1.0/y[49]-1.0));
  JAC(49,0) =  parameters[6]*y[48]*exp(-parameters[5]*(1.0/y[49]-1.0));
  JAC(50,0) =  -y[50]*exp(-parameters[5]*(1.0/y[51]-1.0));
  JAC(51,0) =  parameters[6]*y[50]*exp(-parameters[5]*(1.0/y[51]-1.0));
  JAC(52,0) =  -y[52]*exp(-parameters[5]*(1.0/y[53]-1.0));
  JAC(53,0) =  parameters[6]*y[52]*exp(-parameters[5]*(1.0/y[53]-1.0));
  JAC(54,0) =  -y[54]*exp(-parameters[5]*(1.0/y[55]-1.0));
  JAC(55,0) =  parameters[6]*y[54]*exp(-parameters[5]*(1.0/y[55]-1.0));
  JAC(56,0) =  -y[56]*exp(-parameters[5]*(1.0/y[57]-1.0));
  JAC(57,0) =  parameters[6]*y[56]*exp(-parameters[5]*(1.0/y[57]-1.0));
  JAC(58,0) =  -y[58]*exp(-parameters[5]*(1.0/y[59]-1.0));
  JAC(59,0) =  parameters[6]*y[58]*exp(-parameters[5]*(1.0/y[59]-1.0));
  JAC(60,0) =  -y[60]*exp(-parameters[5]*(1.0/y[61]-1.0));
  JAC(61,0) =  parameters[6]*y[60]*exp(-parameters[5]*(1.0/y[61]-1.0));
  JAC(62,0) =  -y[62]*exp(-parameters[5]*(1.0/y[63]-1.0));
  JAC(63,0) =  parameters[6]*y[62]*exp(-parameters[5]*(1.0/y[63]-1.0));
  JAC(64,0) =  -y[64]*exp(-parameters[5]*(1.0/y[65]-1.0));
  JAC(65,0) =  parameters[6]*y[64]*exp(-parameters[5]*(1.0/y[65]-1.0));
  JAC(66,0) =  -y[66]*exp(-parameters[5]*(1.0/y[67]-1.0));
  JAC(67,0) =  parameters[6]*y[66]*exp(-parameters[5]*(1.0/y[67]-1.0));
  JAC(68,0) =  -y[68]*exp(-parameters[5]*(1.0/y[69]-1.0));
  JAC(69,0) =  parameters[6]*y[68]*exp(-parameters[5]*(1.0/y[69]-1.0));
  JAC(70,0) =  -y[70]*exp(-parameters[5]*(1.0/y[71]-1.0));
  JAC(71,0) =  parameters[6]*y[70]*exp(-parameters[5]*(1.0/y[71]-1.0));
  JAC(72,0) =  -y[72]*exp(-parameters[5]*(1.0/y[73]-1.0));
  JAC(73,0) =  parameters[6]*y[72]*exp(-parameters[5]*(1.0/y[73]-1.0));
  JAC(74,0) =  -y[74]*exp(-parameters[5]*(1.0/y[75]-1.0));
  JAC(75,0) =  parameters[6]*y[74]*exp(-parameters[5]*(1.0/y[75]-1.0));
  JAC(76,0) =  -y[76]*exp(-parameters[5]*(1.0/y[77]-1.0));
  JAC(77,0) =  parameters[6]*y[76]*exp(-parameters[5]*(1.0/y[77]-1.0));
  JAC(78,0) =  -y[78]*exp(-parameters[5]*(1.0/y[79]-1.0));
  JAC(79,0) =  parameters[6]*y[78]*exp(-parameters[5]*(1.0/y[79]-1.0));
  JAC(80,0) =  -y[80]*exp(-parameters[5]*(1.0/y[81]-1.0));
  JAC(81,0) =  parameters[6]*y[80]*exp(-parameters[5]*(1.0/y[81]-1.0));
  JAC(82,0) =  -y[82]*exp(-parameters[5]*(1.0/y[83]-1.0));
  JAC(83,0) =  parameters[6]*y[82]*exp(-parameters[5]*(1.0/y[83]-1.0));
  JAC(84,0) =  -y[84]*exp(-parameters[5]*(1.0/y[85]-1.0));
  JAC(85,0) =  parameters[6]*y[84]*exp(-parameters[5]*(1.0/y[85]-1.0));
  JAC(86,0) =  -y[86]*exp(-parameters[5]*(1.0/y[87]-1.0));
  JAC(87,0) =  parameters[6]*y[86]*exp(-parameters[5]*(1.0/y[87]-1.0));
  JAC(88,0) =  -y[88]*exp(-parameters[5]*(1.0/y[89]-1.0));
  JAC(89,0) =  parameters[6]*y[88]*exp(-parameters[5]*(1.0/y[89]-1.0));
  JAC(90,0) =  -y[90]*exp(-parameters[5]*(1.0/y[91]-1.0));
  JAC(91,0) =  parameters[6]*y[90]*exp(-parameters[5]*(1.0/y[91]-1.0));
  JAC(92,0) =  -y[92]*exp(-parameters[5]*(1.0/y[93]-1.0));
  JAC(93,0) =  parameters[6]*y[92]*exp(-parameters[5]*(1.0/y[93]-1.0));
  JAC(94,0) =  -y[94]*exp(-parameters[5]*(1.0/y[95]-1.0));
  JAC(95,0) =  parameters[6]*y[94]*exp(-parameters[5]*(1.0/y[95]-1.0));
  JAC(96,0) =  -y[96]*exp(-parameters[5]*(1.0/y[97]-1.0));
  JAC(97,0) =  parameters[6]*y[96]*exp(-parameters[5]*(1.0/y[97]-1.0));
  JAC(98,0) =  -y[98]*exp(-parameters[5]*(1.0/y[99]-1.0));
  JAC(99,0) =  parameters[6]*y[98]*exp(-parameters[5]*(1.0/y[99]-1.0));
  JAC(0,1) =  y[0]-(y[0]*9.8E+1-9.8E+1)/parameters[1]+1.0/(parameters[1]*parameters[1])*(y[0]*4.802E+3-y[2]*4.802E+3+parameters[1]*(y[0]-1.0)*9.8E+1)-1.0;
  JAC(2,1) =  -1.0/(parameters[1]*parameters[1])*(y[0]*2.401E+3-y[2]*4.802E+3+y[4]*2.401E+3);
  JAC(4,1) =  -1.0/(parameters[1]*parameters[1])*(y[2]*2.401E+3-y[4]*4.802E+3+y[6]*2.401E+3);
  JAC(6,1) =  -1.0/(parameters[1]*parameters[1])*(y[4]*2.401E+3-y[6]*4.802E+3+y[8]*2.401E+3);
  JAC(8,1) =  -1.0/(parameters[1]*parameters[1])*(y[6]*2.401E+3-y[8]*4.802E+3+y[10]*2.401E+3);
  JAC(10,1) =  -1.0/(parameters[1]*parameters[1])*(y[8]*2.401E+3-y[10]*4.802E+3+y[12]*2.401E+3);
  JAC(12,1) =  -1.0/(parameters[1]*parameters[1])*(y[10]*2.401E+3-y[12]*4.802E+3+y[14]*2.401E+3);
  JAC(14,1) =  -1.0/(parameters[1]*parameters[1])*(y[12]*2.401E+3-y[14]*4.802E+3+y[16]*2.401E+3);
  JAC(16,1) =  -1.0/(parameters[1]*parameters[1])*(y[14]*2.401E+3-y[16]*4.802E+3+y[18]*2.401E+3);
  JAC(18,1) =  -1.0/(parameters[1]*parameters[1])*(y[16]*2.401E+3-y[18]*4.802E+3+y[20]*2.401E+3);
  JAC(20,1) =  -1.0/(parameters[1]*parameters[1])*(y[18]*2.401E+3-y[20]*4.802E+3+y[22]*2.401E+3);
  JAC(22,1) =  -1.0/(parameters[1]*parameters[1])*(y[20]*2.401E+3-y[22]*4.802E+3+y[24]*2.401E+3);
  JAC(24,1) =  -1.0/(parameters[1]*parameters[1])*(y[22]*2.401E+3-y[24]*4.802E+3+y[26]*2.401E+3);
  JAC(26,1) =  -1.0/(parameters[1]*parameters[1])*(y[24]*2.401E+3-y[26]*4.802E+3+y[28]*2.401E+3);
  JAC(28,1) =  -1.0/(parameters[1]*parameters[1])*(y[26]*2.401E+3-y[28]*4.802E+3+y[30]*2.401E+3);
  JAC(30,1) =  -1.0/(parameters[1]*parameters[1])*(y[28]*2.401E+3-y[30]*4.802E+3+y[32]*2.401E+3);
  JAC(32,1) =  -1.0/(parameters[1]*parameters[1])*(y[30]*2.401E+3-y[32]*4.802E+3+y[34]*2.401E+3);
  JAC(34,1) =  -1.0/(parameters[1]*parameters[1])*(y[32]*2.401E+3-y[34]*4.802E+3+y[36]*2.401E+3);
  JAC(36,1) =  -1.0/(parameters[1]*parameters[1])*(y[34]*2.401E+3-y[36]*4.802E+3+y[38]*2.401E+3);
  JAC(38,1) =  -1.0/(parameters[1]*parameters[1])*(y[36]*2.401E+3-y[38]*4.802E+3+y[40]*2.401E+3);
  JAC(40,1) =  -1.0/(parameters[1]*parameters[1])*(y[38]*2.401E+3-y[40]*4.802E+3+y[42]*2.401E+3);
  JAC(42,1) =  -1.0/(parameters[1]*parameters[1])*(y[40]*2.401E+3-y[42]*4.802E+3+y[44]*2.401E+3);
  JAC(44,1) =  -1.0/(parameters[1]*parameters[1])*(y[42]*2.401E+3-y[44]*4.802E+3+y[46]*2.401E+3);
  JAC(46,1) =  -1.0/(parameters[1]*parameters[1])*(y[44]*2.401E+3-y[46]*4.802E+3+y[48]*2.401E+3);
  JAC(48,1) =  -1.0/(parameters[1]*parameters[1])*(y[46]*2.401E+3-y[48]*4.802E+3+y[50]*2.401E+3);
  JAC(50,1) =  -1.0/(parameters[1]*parameters[1])*(y[48]*2.401E+3-y[50]*4.802E+3+y[52]*2.401E+3);
  JAC(52,1) =  -1.0/(parameters[1]*parameters[1])*(y[50]*2.401E+3-y[52]*4.802E+3+y[54]*2.401E+3);
  JAC(54,1) =  -1.0/(parameters[1]*parameters[1])*(y[52]*2.401E+3-y[54]*4.802E+3+y[56]*2.401E+3);
  JAC(56,1) =  -1.0/(parameters[1]*parameters[1])*(y[54]*2.401E+3-y[56]*4.802E+3+y[58]*2.401E+3);
  JAC(58,1) =  -1.0/(parameters[1]*parameters[1])*(y[56]*2.401E+3-y[58]*4.802E+3+y[60]*2.401E+3);
  JAC(60,1) =  -1.0/(parameters[1]*parameters[1])*(y[58]*2.401E+3-y[60]*4.802E+3+y[62]*2.401E+3);
  JAC(62,1) =  -1.0/(parameters[1]*parameters[1])*(y[60]*2.401E+3-y[62]*4.802E+3+y[64]*2.401E+3);
  JAC(64,1) =  -1.0/(parameters[1]*parameters[1])*(y[62]*2.401E+3-y[64]*4.802E+3+y[66]*2.401E+3);
  JAC(66,1) =  -1.0/(parameters[1]*parameters[1])*(y[64]*2.401E+3-y[66]*4.802E+3+y[68]*2.401E+3);
  JAC(68,1) =  -1.0/(parameters[1]*parameters[1])*(y[66]*2.401E+3-y[68]*4.802E+3+y[70]*2.401E+3);
  JAC(70,1) =  -1.0/(parameters[1]*parameters[1])*(y[68]*2.401E+3-y[70]*4.802E+3+y[72]*2.401E+3);
  JAC(72,1) =  -1.0/(parameters[1]*parameters[1])*(y[70]*2.401E+3-y[72]*4.802E+3+y[74]*2.401E+3);
  JAC(74,1) =  -1.0/(parameters[1]*parameters[1])*(y[72]*2.401E+3-y[74]*4.802E+3+y[76]*2.401E+3);
  JAC(76,1) =  -1.0/(parameters[1]*parameters[1])*(y[74]*2.401E+3-y[76]*4.802E+3+y[78]*2.401E+3);
  JAC(78,1) =  -1.0/(parameters[1]*parameters[1])*(y[76]*2.401E+3-y[78]*4.802E+3+y[80]*2.401E+3);
  JAC(80,1) =  -1.0/(parameters[1]*parameters[1])*(y[78]*2.401E+3-y[80]*4.802E+3+y[82]*2.401E+3);
  JAC(82,1) =  -1.0/(parameters[1]*parameters[1])*(y[80]*2.401E+3-y[82]*4.802E+3+y[84]*2.401E+3);
  JAC(84,1) =  -1.0/(parameters[1]*parameters[1])*(y[82]*2.401E+3-y[84]*4.802E+3+y[86]*2.401E+3);
  JAC(86,1) =  -1.0/(parameters[1]*parameters[1])*(y[84]*2.401E+3-y[86]*4.802E+3+y[88]*2.401E+3);
  JAC(88,1) =  -1.0/(parameters[1]*parameters[1])*(y[86]*2.401E+3-y[88]*4.802E+3+y[90]*2.401E+3);
  JAC(90,1) =  -1.0/(parameters[1]*parameters[1])*(y[88]*2.401E+3-y[90]*4.802E+3+y[92]*2.401E+3);
  JAC(92,1) =  -1.0/(parameters[1]*parameters[1])*(y[90]*2.401E+3-y[92]*4.802E+3+y[94]*2.401E+3);
  JAC(94,1) =  -1.0/(parameters[1]*parameters[1])*(y[92]*2.401E+3-y[94]*4.802E+3+y[96]*2.401E+3);
  JAC(96,1) =  -1.0/(parameters[1]*parameters[1])*(y[94]*2.401E+3-y[96]*4.802E+3+y[98]*2.401E+3);
  JAC(98,1) =  -1.0/(parameters[1]*parameters[1])*(y[96]*4.802E+3-y[98]*4.802E+3);
  JAC(1,2) =  y[1]-(y[1]*9.8E+1-9.8E+1)/parameters[2]+1.0/(parameters[2]*parameters[2])*(y[1]*4.802E+3-y[3]*4.802E+3+parameters[2]*(y[1]-1.0)*9.8E+1)-1.0;
  JAC(3,2) =  -1.0/(parameters[2]*parameters[2])*(y[1]*2.401E+3-y[3]*4.802E+3+y[5]*2.401E+3);
  JAC(5,2) =  -1.0/(parameters[2]*parameters[2])*(y[3]*2.401E+3-y[5]*4.802E+3+y[7]*2.401E+3);
  JAC(7,2) =  -1.0/(parameters[2]*parameters[2])*(y[5]*2.401E+3-y[7]*4.802E+3+y[9]*2.401E+3);
  JAC(9,2) =  -1.0/(parameters[2]*parameters[2])*(y[7]*2.401E+3-y[9]*4.802E+3+y[11]*2.401E+3);
  JAC(11,2) =  -1.0/(parameters[2]*parameters[2])*(y[9]*2.401E+3-y[11]*4.802E+3+y[13]*2.401E+3);
  JAC(13,2) =  -1.0/(parameters[2]*parameters[2])*(y[11]*2.401E+3-y[13]*4.802E+3+y[15]*2.401E+3);
  JAC(15,2) =  -1.0/(parameters[2]*parameters[2])*(y[13]*2.401E+3-y[15]*4.802E+3+y[17]*2.401E+3);
  JAC(17,2) =  -1.0/(parameters[2]*parameters[2])*(y[15]*2.401E+3-y[17]*4.802E+3+y[19]*2.401E+3);
  JAC(19,2) =  -1.0/(parameters[2]*parameters[2])*(y[17]*2.401E+3-y[19]*4.802E+3+y[21]*2.401E+3);
  JAC(21,2) =  -1.0/(parameters[2]*parameters[2])*(y[19]*2.401E+3-y[21]*4.802E+3+y[23]*2.401E+3);
  JAC(23,2) =  -1.0/(parameters[2]*parameters[2])*(y[21]*2.401E+3-y[23]*4.802E+3+y[25]*2.401E+3);
  JAC(25,2) =  -1.0/(parameters[2]*parameters[2])*(y[23]*2.401E+3-y[25]*4.802E+3+y[27]*2.401E+3);
  JAC(27,2) =  -1.0/(parameters[2]*parameters[2])*(y[25]*2.401E+3-y[27]*4.802E+3+y[29]*2.401E+3);
  JAC(29,2) =  -1.0/(parameters[2]*parameters[2])*(y[27]*2.401E+3-y[29]*4.802E+3+y[31]*2.401E+3);
  JAC(31,2) =  -1.0/(parameters[2]*parameters[2])*(y[29]*2.401E+3-y[31]*4.802E+3+y[33]*2.401E+3);
  JAC(33,2) =  -1.0/(parameters[2]*parameters[2])*(y[31]*2.401E+3-y[33]*4.802E+3+y[35]*2.401E+3);
  JAC(35,2) =  -1.0/(parameters[2]*parameters[2])*(y[33]*2.401E+3-y[35]*4.802E+3+y[37]*2.401E+3);
  JAC(37,2) =  -1.0/(parameters[2]*parameters[2])*(y[35]*2.401E+3-y[37]*4.802E+3+y[39]*2.401E+3);
  JAC(39,2) =  -1.0/(parameters[2]*parameters[2])*(y[37]*2.401E+3-y[39]*4.802E+3+y[41]*2.401E+3);
  JAC(41,2) =  -1.0/(parameters[2]*parameters[2])*(y[39]*2.401E+3-y[41]*4.802E+3+y[43]*2.401E+3);
  JAC(43,2) =  -1.0/(parameters[2]*parameters[2])*(y[41]*2.401E+3-y[43]*4.802E+3+y[45]*2.401E+3);
  JAC(45,2) =  -1.0/(parameters[2]*parameters[2])*(y[43]*2.401E+3-y[45]*4.802E+3+y[47]*2.401E+3);
  JAC(47,2) =  -1.0/(parameters[2]*parameters[2])*(y[45]*2.401E+3-y[47]*4.802E+3+y[49]*2.401E+3);
  JAC(49,2) =  -1.0/(parameters[2]*parameters[2])*(y[47]*2.401E+3-y[49]*4.802E+3+y[51]*2.401E+3);
  JAC(51,2) =  -1.0/(parameters[2]*parameters[2])*(y[49]*2.401E+3-y[51]*4.802E+3+y[53]*2.401E+3);
  JAC(53,2) =  -1.0/(parameters[2]*parameters[2])*(y[51]*2.401E+3-y[53]*4.802E+3+y[55]*2.401E+3);
  JAC(55,2) =  -1.0/(parameters[2]*parameters[2])*(y[53]*2.401E+3-y[55]*4.802E+3+y[57]*2.401E+3);
  JAC(57,2) =  -1.0/(parameters[2]*parameters[2])*(y[55]*2.401E+3-y[57]*4.802E+3+y[59]*2.401E+3);
  JAC(59,2) =  -1.0/(parameters[2]*parameters[2])*(y[57]*2.401E+3-y[59]*4.802E+3+y[61]*2.401E+3);
  JAC(61,2) =  -1.0/(parameters[2]*parameters[2])*(y[59]*2.401E+3-y[61]*4.802E+3+y[63]*2.401E+3);
  JAC(63,2) =  -1.0/(parameters[2]*parameters[2])*(y[61]*2.401E+3-y[63]*4.802E+3+y[65]*2.401E+3);
  JAC(65,2) =  -1.0/(parameters[2]*parameters[2])*(y[63]*2.401E+3-y[65]*4.802E+3+y[67]*2.401E+3);
  JAC(67,2) =  -1.0/(parameters[2]*parameters[2])*(y[65]*2.401E+3-y[67]*4.802E+3+y[69]*2.401E+3);
  JAC(69,2) =  -1.0/(parameters[2]*parameters[2])*(y[67]*2.401E+3-y[69]*4.802E+3+y[71]*2.401E+3);
  JAC(71,2) =  -1.0/(parameters[2]*parameters[2])*(y[69]*2.401E+3-y[71]*4.802E+3+y[73]*2.401E+3);
  JAC(73,2) =  -1.0/(parameters[2]*parameters[2])*(y[71]*2.401E+3-y[73]*4.802E+3+y[75]*2.401E+3);
  JAC(75,2) =  -1.0/(parameters[2]*parameters[2])*(y[73]*2.401E+3-y[75]*4.802E+3+y[77]*2.401E+3);
  JAC(77,2) =  -1.0/(parameters[2]*parameters[2])*(y[75]*2.401E+3-y[77]*4.802E+3+y[79]*2.401E+3);
  JAC(79,2) =  -1.0/(parameters[2]*parameters[2])*(y[77]*2.401E+3-y[79]*4.802E+3+y[81]*2.401E+3);
  JAC(81,2) =  -1.0/(parameters[2]*parameters[2])*(y[79]*2.401E+3-y[81]*4.802E+3+y[83]*2.401E+3);
  JAC(83,2) =  -1.0/(parameters[2]*parameters[2])*(y[81]*2.401E+3-y[83]*4.802E+3+y[85]*2.401E+3);
  JAC(85,2) =  -1.0/(parameters[2]*parameters[2])*(y[83]*2.401E+3-y[85]*4.802E+3+y[87]*2.401E+3);
  JAC(87,2) =  -1.0/(parameters[2]*parameters[2])*(y[85]*2.401E+3-y[87]*4.802E+3+y[89]*2.401E+3);
  JAC(89,2) =  -1.0/(parameters[2]*parameters[2])*(y[87]*2.401E+3-y[89]*4.802E+3+y[91]*2.401E+3);
  JAC(91,2) =  -1.0/(parameters[2]*parameters[2])*(y[89]*2.401E+3-y[91]*4.802E+3+y[93]*2.401E+3);
  JAC(93,2) =  -1.0/(parameters[2]*parameters[2])*(y[91]*2.401E+3-y[93]*4.802E+3+y[95]*2.401E+3);
  JAC(95,2) =  -1.0/(parameters[2]*parameters[2])*(y[93]*2.401E+3-y[95]*4.802E+3+y[97]*2.401E+3);
  JAC(97,2) =  -1.0/(parameters[2]*parameters[2])*(y[95]*2.401E+3-y[97]*4.802E+3+y[99]*2.401E+3);
  JAC(99,2) =  -1.0/(parameters[2]*parameters[2])*(y[97]*4.802E+3-y[99]*4.802E+3);
  JAC(1,3) =  parameters[4]-y[1];
  JAC(3,3) =  parameters[4]-y[3];
  JAC(5,3) =  parameters[4]-y[5];
  JAC(7,3) =  parameters[4]-y[7];
  JAC(9,3) =  parameters[4]-y[9];
  JAC(11,3) =  parameters[4]-y[11];
  JAC(13,3) =  parameters[4]-y[13];
  JAC(15,3) =  parameters[4]-y[15];
  JAC(17,3) =  parameters[4]-y[17];
  JAC(19,3) =  parameters[4]-y[19];
  JAC(21,3) =  parameters[4]-y[21];
  JAC(23,3) =  parameters[4]-y[23];
  JAC(25,3) =  parameters[4]-y[25];
  JAC(27,3) =  parameters[4]-y[27];
  JAC(29,3) =  parameters[4]-y[29];
  JAC(31,3) =  parameters[4]-y[31];
  JAC(33,3) =  parameters[4]-y[33];
  JAC(35,3) =  parameters[4]-y[35];
  JAC(37,3) =  parameters[4]-y[37];
  JAC(39,3) =  parameters[4]-y[39];
  JAC(41,3) =  parameters[4]-y[41];
  JAC(43,3) =  parameters[4]-y[43];
  JAC(45,3) =  parameters[4]-y[45];
  JAC(47,3) =  parameters[4]-y[47];
  JAC(49,3) =  parameters[4]-y[49];
  JAC(51,3) =  parameters[4]-y[51];
  JAC(53,3) =  parameters[4]-y[53];
  JAC(55,3) =  parameters[4]-y[55];
  JAC(57,3) =  parameters[4]-y[57];
  JAC(59,3) =  parameters[4]-y[59];
  JAC(61,3) =  parameters[4]-y[61];
  JAC(63,3) =  parameters[4]-y[63];
  JAC(65,3) =  parameters[4]-y[65];
  JAC(67,3) =  parameters[4]-y[67];
  JAC(69,3) =  parameters[4]-y[69];
  JAC(71,3) =  parameters[4]-y[71];
  JAC(73,3) =  parameters[4]-y[73];
  JAC(75,3) =  parameters[4]-y[75];
  JAC(77,3) =  parameters[4]-y[77];
  JAC(79,3) =  parameters[4]-y[79];
  JAC(81,3) =  parameters[4]-y[81];
  JAC(83,3) =  parameters[4]-y[83];
  JAC(85,3) =  parameters[4]-y[85];
  JAC(87,3) =  parameters[4]-y[87];
  JAC(89,3) =  parameters[4]-y[89];
  JAC(91,3) =  parameters[4]-y[91];
  JAC(93,3) =  parameters[4]-y[93];
  JAC(95,3) =  parameters[4]-y[95];
  JAC(97,3) =  parameters[4]-y[97];
  JAC(99,3) =  parameters[4]-y[99];
  JAC(1,4) =  parameters[3];
  JAC(3,4) =  parameters[3];
  JAC(5,4) =  parameters[3];
  JAC(7,4) =  parameters[3];
  JAC(9,4) =  parameters[3];
  JAC(11,4) =  parameters[3];
  JAC(13,4) =  parameters[3];
  JAC(15,4) =  parameters[3];
  JAC(17,4) =  parameters[3];
  JAC(19,4) =  parameters[3];
  JAC(21,4) =  parameters[3];
  JAC(23,4) =  parameters[3];
  JAC(25,4) =  parameters[3];
  JAC(27,4) =  parameters[3];
  JAC(29,4) =  parameters[3];
  JAC(31,4) =  parameters[3];
  JAC(33,4) =  parameters[3];
  JAC(35,4) =  parameters[3];
  JAC(37,4) =  parameters[3];
  JAC(39,4) =  parameters[3];
  JAC(41,4) =  parameters[3];
  JAC(43,4) =  parameters[3];
  JAC(45,4) =  parameters[3];
  JAC(47,4) =  parameters[3];
  JAC(49,4) =  parameters[3];
  JAC(51,4) =  parameters[3];
  JAC(53,4) =  parameters[3];
  JAC(55,4) =  parameters[3];
  JAC(57,4) =  parameters[3];
  JAC(59,4) =  parameters[3];
  JAC(61,4) =  parameters[3];
  JAC(63,4) =  parameters[3];
  JAC(65,4) =  parameters[3];
  JAC(67,4) =  parameters[3];
  JAC(69,4) =  parameters[3];
  JAC(71,4) =  parameters[3];
  JAC(73,4) =  parameters[3];
  JAC(75,4) =  parameters[3];
  JAC(77,4) =  parameters[3];
  JAC(79,4) =  parameters[3];
  JAC(81,4) =  parameters[3];
  JAC(83,4) =  parameters[3];
  JAC(85,4) =  parameters[3];
  JAC(87,4) =  parameters[3];
  JAC(89,4) =  parameters[3];
  JAC(91,4) =  parameters[3];
  JAC(93,4) =  parameters[3];
  JAC(95,4) =  parameters[3];
  JAC(97,4) =  parameters[3];
  JAC(99,4) =  parameters[3];
  JAC(0,5) =  parameters[0]*y[0]*exp(-parameters[5]*(1.0/y[1]-1.0))*(1.0/y[1]-1.0);
  JAC(1,5) =  -parameters[6]*parameters[0]*y[0]*exp(-parameters[5]*(1.0/y[1]-1.0))*(1.0/y[1]-1.0);
  JAC(2,5) =  parameters[0]*y[2]*exp(-parameters[5]*(1.0/y[3]-1.0))*(1.0/y[3]-1.0);
  JAC(3,5) =  -parameters[6]*parameters[0]*y[2]*exp(-parameters[5]*(1.0/y[3]-1.0))*(1.0/y[3]-1.0);
  JAC(4,5) =  parameters[0]*y[4]*exp(-parameters[5]*(1.0/y[5]-1.0))*(1.0/y[5]-1.0);
  JAC(5,5) =  -parameters[6]*parameters[0]*y[4]*exp(-parameters[5]*(1.0/y[5]-1.0))*(1.0/y[5]-1.0);
  JAC(6,5) =  parameters[0]*y[6]*exp(-parameters[5]*(1.0/y[7]-1.0))*(1.0/y[7]-1.0);
  JAC(7,5) =  -parameters[6]*parameters[0]*y[6]*exp(-parameters[5]*(1.0/y[7]-1.0))*(1.0/y[7]-1.0);
  JAC(8,5) =  parameters[0]*y[8]*exp(-parameters[5]*(1.0/y[9]-1.0))*(1.0/y[9]-1.0);
  JAC(9,5) =  -parameters[6]*parameters[0]*y[8]*exp(-parameters[5]*(1.0/y[9]-1.0))*(1.0/y[9]-1.0);
  JAC(10,5) =  parameters[0]*y[10]*exp(-parameters[5]*(1.0/y[11]-1.0))*(1.0/y[11]-1.0);
  JAC(11,5) =  -parameters[6]*parameters[0]*y[10]*exp(-parameters[5]*(1.0/y[11]-1.0))*(1.0/y[11]-1.0);
  JAC(12,5) =  parameters[0]*y[12]*exp(-parameters[5]*(1.0/y[13]-1.0))*(1.0/y[13]-1.0);
  JAC(13,5) =  -parameters[6]*parameters[0]*y[12]*exp(-parameters[5]*(1.0/y[13]-1.0))*(1.0/y[13]-1.0);
  JAC(14,5) =  parameters[0]*y[14]*exp(-parameters[5]*(1.0/y[15]-1.0))*(1.0/y[15]-1.0);
  JAC(15,5) =  -parameters[6]*parameters[0]*y[14]*exp(-parameters[5]*(1.0/y[15]-1.0))*(1.0/y[15]-1.0);
  JAC(16,5) =  parameters[0]*y[16]*exp(-parameters[5]*(1.0/y[17]-1.0))*(1.0/y[17]-1.0);
  JAC(17,5) =  -parameters[6]*parameters[0]*y[16]*exp(-parameters[5]*(1.0/y[17]-1.0))*(1.0/y[17]-1.0);
  JAC(18,5) =  parameters[0]*y[18]*exp(-parameters[5]*(1.0/y[19]-1.0))*(1.0/y[19]-1.0);
  JAC(19,5) =  -parameters[6]*parameters[0]*y[18]*exp(-parameters[5]*(1.0/y[19]-1.0))*(1.0/y[19]-1.0);
  JAC(20,5) =  parameters[0]*y[20]*exp(-parameters[5]*(1.0/y[21]-1.0))*(1.0/y[21]-1.0);
  JAC(21,5) =  -parameters[6]*parameters[0]*y[20]*exp(-parameters[5]*(1.0/y[21]-1.0))*(1.0/y[21]-1.0);
  JAC(22,5) =  parameters[0]*y[22]*exp(-parameters[5]*(1.0/y[23]-1.0))*(1.0/y[23]-1.0);
  JAC(23,5) =  -parameters[6]*parameters[0]*y[22]*exp(-parameters[5]*(1.0/y[23]-1.0))*(1.0/y[23]-1.0);
  JAC(24,5) =  parameters[0]*y[24]*exp(-parameters[5]*(1.0/y[25]-1.0))*(1.0/y[25]-1.0);
  JAC(25,5) =  -parameters[6]*parameters[0]*y[24]*exp(-parameters[5]*(1.0/y[25]-1.0))*(1.0/y[25]-1.0);
  JAC(26,5) =  parameters[0]*y[26]*exp(-parameters[5]*(1.0/y[27]-1.0))*(1.0/y[27]-1.0);
  JAC(27,5) =  -parameters[6]*parameters[0]*y[26]*exp(-parameters[5]*(1.0/y[27]-1.0))*(1.0/y[27]-1.0);
  JAC(28,5) =  parameters[0]*y[28]*exp(-parameters[5]*(1.0/y[29]-1.0))*(1.0/y[29]-1.0);
  JAC(29,5) =  -parameters[6]*parameters[0]*y[28]*exp(-parameters[5]*(1.0/y[29]-1.0))*(1.0/y[29]-1.0);
  JAC(30,5) =  parameters[0]*y[30]*exp(-parameters[5]*(1.0/y[31]-1.0))*(1.0/y[31]-1.0);
  JAC(31,5) =  -parameters[6]*parameters[0]*y[30]*exp(-parameters[5]*(1.0/y[31]-1.0))*(1.0/y[31]-1.0);
  JAC(32,5) =  parameters[0]*y[32]*exp(-parameters[5]*(1.0/y[33]-1.0))*(1.0/y[33]-1.0);
  JAC(33,5) =  -parameters[6]*parameters[0]*y[32]*exp(-parameters[5]*(1.0/y[33]-1.0))*(1.0/y[33]-1.0);
  JAC(34,5) =  parameters[0]*y[34]*exp(-parameters[5]*(1.0/y[35]-1.0))*(1.0/y[35]-1.0);
  JAC(35,5) =  -parameters[6]*parameters[0]*y[34]*exp(-parameters[5]*(1.0/y[35]-1.0))*(1.0/y[35]-1.0);
  JAC(36,5) =  parameters[0]*y[36]*exp(-parameters[5]*(1.0/y[37]-1.0))*(1.0/y[37]-1.0);
  JAC(37,5) =  -parameters[6]*parameters[0]*y[36]*exp(-parameters[5]*(1.0/y[37]-1.0))*(1.0/y[37]-1.0);
  JAC(38,5) =  parameters[0]*y[38]*exp(-parameters[5]*(1.0/y[39]-1.0))*(1.0/y[39]-1.0);
  JAC(39,5) =  -parameters[6]*parameters[0]*y[38]*exp(-parameters[5]*(1.0/y[39]-1.0))*(1.0/y[39]-1.0);
  JAC(40,5) =  parameters[0]*y[40]*exp(-parameters[5]*(1.0/y[41]-1.0))*(1.0/y[41]-1.0);
  JAC(41,5) =  -parameters[6]*parameters[0]*y[40]*exp(-parameters[5]*(1.0/y[41]-1.0))*(1.0/y[41]-1.0);
  JAC(42,5) =  parameters[0]*y[42]*exp(-parameters[5]*(1.0/y[43]-1.0))*(1.0/y[43]-1.0);
  JAC(43,5) =  -parameters[6]*parameters[0]*y[42]*exp(-parameters[5]*(1.0/y[43]-1.0))*(1.0/y[43]-1.0);
  JAC(44,5) =  parameters[0]*y[44]*exp(-parameters[5]*(1.0/y[45]-1.0))*(1.0/y[45]-1.0);
  JAC(45,5) =  -parameters[6]*parameters[0]*y[44]*exp(-parameters[5]*(1.0/y[45]-1.0))*(1.0/y[45]-1.0);
  JAC(46,5) =  parameters[0]*y[46]*exp(-parameters[5]*(1.0/y[47]-1.0))*(1.0/y[47]-1.0);
  JAC(47,5) =  -parameters[6]*parameters[0]*y[46]*exp(-parameters[5]*(1.0/y[47]-1.0))*(1.0/y[47]-1.0);
  JAC(48,5) =  parameters[0]*y[48]*exp(-parameters[5]*(1.0/y[49]-1.0))*(1.0/y[49]-1.0);
  JAC(49,5) =  -parameters[6]*parameters[0]*y[48]*exp(-parameters[5]*(1.0/y[49]-1.0))*(1.0/y[49]-1.0);
  JAC(50,5) =  parameters[0]*y[50]*exp(-parameters[5]*(1.0/y[51]-1.0))*(1.0/y[51]-1.0);
  JAC(51,5) =  -parameters[6]*parameters[0]*y[50]*exp(-parameters[5]*(1.0/y[51]-1.0))*(1.0/y[51]-1.0);
  JAC(52,5) =  parameters[0]*y[52]*exp(-parameters[5]*(1.0/y[53]-1.0))*(1.0/y[53]-1.0);
  JAC(53,5) =  -parameters[6]*parameters[0]*y[52]*exp(-parameters[5]*(1.0/y[53]-1.0))*(1.0/y[53]-1.0);
  JAC(54,5) =  parameters[0]*y[54]*exp(-parameters[5]*(1.0/y[55]-1.0))*(1.0/y[55]-1.0);
  JAC(55,5) =  -parameters[6]*parameters[0]*y[54]*exp(-parameters[5]*(1.0/y[55]-1.0))*(1.0/y[55]-1.0);
  JAC(56,5) =  parameters[0]*y[56]*exp(-parameters[5]*(1.0/y[57]-1.0))*(1.0/y[57]-1.0);
  JAC(57,5) =  -parameters[6]*parameters[0]*y[56]*exp(-parameters[5]*(1.0/y[57]-1.0))*(1.0/y[57]-1.0);
  JAC(58,5) =  parameters[0]*y[58]*exp(-parameters[5]*(1.0/y[59]-1.0))*(1.0/y[59]-1.0);
  JAC(59,5) =  -parameters[6]*parameters[0]*y[58]*exp(-parameters[5]*(1.0/y[59]-1.0))*(1.0/y[59]-1.0);
  JAC(60,5) =  parameters[0]*y[60]*exp(-parameters[5]*(1.0/y[61]-1.0))*(1.0/y[61]-1.0);
  JAC(61,5) =  -parameters[6]*parameters[0]*y[60]*exp(-parameters[5]*(1.0/y[61]-1.0))*(1.0/y[61]-1.0);
  JAC(62,5) =  parameters[0]*y[62]*exp(-parameters[5]*(1.0/y[63]-1.0))*(1.0/y[63]-1.0);
  JAC(63,5) =  -parameters[6]*parameters[0]*y[62]*exp(-parameters[5]*(1.0/y[63]-1.0))*(1.0/y[63]-1.0);
  JAC(64,5) =  parameters[0]*y[64]*exp(-parameters[5]*(1.0/y[65]-1.0))*(1.0/y[65]-1.0);
  JAC(65,5) =  -parameters[6]*parameters[0]*y[64]*exp(-parameters[5]*(1.0/y[65]-1.0))*(1.0/y[65]-1.0);
  JAC(66,5) =  parameters[0]*y[66]*exp(-parameters[5]*(1.0/y[67]-1.0))*(1.0/y[67]-1.0);
  JAC(67,5) =  -parameters[6]*parameters[0]*y[66]*exp(-parameters[5]*(1.0/y[67]-1.0))*(1.0/y[67]-1.0);
  JAC(68,5) =  parameters[0]*y[68]*exp(-parameters[5]*(1.0/y[69]-1.0))*(1.0/y[69]-1.0);
  JAC(69,5) =  -parameters[6]*parameters[0]*y[68]*exp(-parameters[5]*(1.0/y[69]-1.0))*(1.0/y[69]-1.0);
  JAC(70,5) =  parameters[0]*y[70]*exp(-parameters[5]*(1.0/y[71]-1.0))*(1.0/y[71]-1.0);
  JAC(71,5) =  -parameters[6]*parameters[0]*y[70]*exp(-parameters[5]*(1.0/y[71]-1.0))*(1.0/y[71]-1.0);
  JAC(72,5) =  parameters[0]*y[72]*exp(-parameters[5]*(1.0/y[73]-1.0))*(1.0/y[73]-1.0);
  JAC(73,5) =  -parameters[6]*parameters[0]*y[72]*exp(-parameters[5]*(1.0/y[73]-1.0))*(1.0/y[73]-1.0);
  JAC(74,5) =  parameters[0]*y[74]*exp(-parameters[5]*(1.0/y[75]-1.0))*(1.0/y[75]-1.0);
  JAC(75,5) =  -parameters[6]*parameters[0]*y[74]*exp(-parameters[5]*(1.0/y[75]-1.0))*(1.0/y[75]-1.0);
  JAC(76,5) =  parameters[0]*y[76]*exp(-parameters[5]*(1.0/y[77]-1.0))*(1.0/y[77]-1.0);
  JAC(77,5) =  -parameters[6]*parameters[0]*y[76]*exp(-parameters[5]*(1.0/y[77]-1.0))*(1.0/y[77]-1.0);
  JAC(78,5) =  parameters[0]*y[78]*exp(-parameters[5]*(1.0/y[79]-1.0))*(1.0/y[79]-1.0);
  JAC(79,5) =  -parameters[6]*parameters[0]*y[78]*exp(-parameters[5]*(1.0/y[79]-1.0))*(1.0/y[79]-1.0);
  JAC(80,5) =  parameters[0]*y[80]*exp(-parameters[5]*(1.0/y[81]-1.0))*(1.0/y[81]-1.0);
  JAC(81,5) =  -parameters[6]*parameters[0]*y[80]*exp(-parameters[5]*(1.0/y[81]-1.0))*(1.0/y[81]-1.0);
  JAC(82,5) =  parameters[0]*y[82]*exp(-parameters[5]*(1.0/y[83]-1.0))*(1.0/y[83]-1.0);
  JAC(83,5) =  -parameters[6]*parameters[0]*y[82]*exp(-parameters[5]*(1.0/y[83]-1.0))*(1.0/y[83]-1.0);
  JAC(84,5) =  parameters[0]*y[84]*exp(-parameters[5]*(1.0/y[85]-1.0))*(1.0/y[85]-1.0);
  JAC(85,5) =  -parameters[6]*parameters[0]*y[84]*exp(-parameters[5]*(1.0/y[85]-1.0))*(1.0/y[85]-1.0);
  JAC(86,5) =  parameters[0]*y[86]*exp(-parameters[5]*(1.0/y[87]-1.0))*(1.0/y[87]-1.0);
  JAC(87,5) =  -parameters[6]*parameters[0]*y[86]*exp(-parameters[5]*(1.0/y[87]-1.0))*(1.0/y[87]-1.0);
  JAC(88,5) =  parameters[0]*y[88]*exp(-parameters[5]*(1.0/y[89]-1.0))*(1.0/y[89]-1.0);
  JAC(89,5) =  -parameters[6]*parameters[0]*y[88]*exp(-parameters[5]*(1.0/y[89]-1.0))*(1.0/y[89]-1.0);
  JAC(90,5) =  parameters[0]*y[90]*exp(-parameters[5]*(1.0/y[91]-1.0))*(1.0/y[91]-1.0);
  JAC(91,5) =  -parameters[6]*parameters[0]*y[90]*exp(-parameters[5]*(1.0/y[91]-1.0))*(1.0/y[91]-1.0);
  JAC(92,5) =  parameters[0]*y[92]*exp(-parameters[5]*(1.0/y[93]-1.0))*(1.0/y[93]-1.0);
  JAC(93,5) =  -parameters[6]*parameters[0]*y[92]*exp(-parameters[5]*(1.0/y[93]-1.0))*(1.0/y[93]-1.0);
  JAC(94,5) =  parameters[0]*y[94]*exp(-parameters[5]*(1.0/y[95]-1.0))*(1.0/y[95]-1.0);
  JAC(95,5) =  -parameters[6]*parameters[0]*y[94]*exp(-parameters[5]*(1.0/y[95]-1.0))*(1.0/y[95]-1.0);
  JAC(96,5) =  parameters[0]*y[96]*exp(-parameters[5]*(1.0/y[97]-1.0))*(1.0/y[97]-1.0);
  JAC(97,5) =  -parameters[6]*parameters[0]*y[96]*exp(-parameters[5]*(1.0/y[97]-1.0))*(1.0/y[97]-1.0);
  JAC(98,5) =  parameters[0]*y[98]*exp(-parameters[5]*(1.0/y[99]-1.0))*(1.0/y[99]-1.0);
  JAC(99,5) =  -parameters[6]*parameters[0]*y[98]*exp(-parameters[5]*(1.0/y[99]-1.0))*(1.0/y[99]-1.0);
  JAC(1,6) =  parameters[0]*y[0]*exp(-parameters[5]*(1.0/y[1]-1.0));
  JAC(3,6) =  parameters[0]*y[2]*exp(-parameters[5]*(1.0/y[3]-1.0));
  JAC(5,6) =  parameters[0]*y[4]*exp(-parameters[5]*(1.0/y[5]-1.0));
  JAC(7,6) =  parameters[0]*y[6]*exp(-parameters[5]*(1.0/y[7]-1.0));
  JAC(9,6) =  parameters[0]*y[8]*exp(-parameters[5]*(1.0/y[9]-1.0));
  JAC(11,6) =  parameters[0]*y[10]*exp(-parameters[5]*(1.0/y[11]-1.0));
  JAC(13,6) =  parameters[0]*y[12]*exp(-parameters[5]*(1.0/y[13]-1.0));
  JAC(15,6) =  parameters[0]*y[14]*exp(-parameters[5]*(1.0/y[15]-1.0));
  JAC(17,6) =  parameters[0]*y[16]*exp(-parameters[5]*(1.0/y[17]-1.0));
  JAC(19,6) =  parameters[0]*y[18]*exp(-parameters[5]*(1.0/y[19]-1.0));
  JAC(21,6) =  parameters[0]*y[20]*exp(-parameters[5]*(1.0/y[21]-1.0));
  JAC(23,6) =  parameters[0]*y[22]*exp(-parameters[5]*(1.0/y[23]-1.0));
  JAC(25,6) =  parameters[0]*y[24]*exp(-parameters[5]*(1.0/y[25]-1.0));
  JAC(27,6) =  parameters[0]*y[26]*exp(-parameters[5]*(1.0/y[27]-1.0));
  JAC(29,6) =  parameters[0]*y[28]*exp(-parameters[5]*(1.0/y[29]-1.0));
  JAC(31,6) =  parameters[0]*y[30]*exp(-parameters[5]*(1.0/y[31]-1.0));
  JAC(33,6) =  parameters[0]*y[32]*exp(-parameters[5]*(1.0/y[33]-1.0));
  JAC(35,6) =  parameters[0]*y[34]*exp(-parameters[5]*(1.0/y[35]-1.0));
  JAC(37,6) =  parameters[0]*y[36]*exp(-parameters[5]*(1.0/y[37]-1.0));
  JAC(39,6) =  parameters[0]*y[38]*exp(-parameters[5]*(1.0/y[39]-1.0));
  JAC(41,6) =  parameters[0]*y[40]*exp(-parameters[5]*(1.0/y[41]-1.0));
  JAC(43,6) =  parameters[0]*y[42]*exp(-parameters[5]*(1.0/y[43]-1.0));
  JAC(45,6) =  parameters[0]*y[44]*exp(-parameters[5]*(1.0/y[45]-1.0));
  JAC(47,6) =  parameters[0]*y[46]*exp(-parameters[5]*(1.0/y[47]-1.0));
  JAC(49,6) =  parameters[0]*y[48]*exp(-parameters[5]*(1.0/y[49]-1.0));
  JAC(51,6) =  parameters[0]*y[50]*exp(-parameters[5]*(1.0/y[51]-1.0));
  JAC(53,6) =  parameters[0]*y[52]*exp(-parameters[5]*(1.0/y[53]-1.0));
  JAC(55,6) =  parameters[0]*y[54]*exp(-parameters[5]*(1.0/y[55]-1.0));
  JAC(57,6) =  parameters[0]*y[56]*exp(-parameters[5]*(1.0/y[57]-1.0));
  JAC(59,6) =  parameters[0]*y[58]*exp(-parameters[5]*(1.0/y[59]-1.0));
  JAC(61,6) =  parameters[0]*y[60]*exp(-parameters[5]*(1.0/y[61]-1.0));
  JAC(63,6) =  parameters[0]*y[62]*exp(-parameters[5]*(1.0/y[63]-1.0));
  JAC(65,6) =  parameters[0]*y[64]*exp(-parameters[5]*(1.0/y[65]-1.0));
  JAC(67,6) =  parameters[0]*y[66]*exp(-parameters[5]*(1.0/y[67]-1.0));
  JAC(69,6) =  parameters[0]*y[68]*exp(-parameters[5]*(1.0/y[69]-1.0));
  JAC(71,6) =  parameters[0]*y[70]*exp(-parameters[5]*(1.0/y[71]-1.0));
  JAC(73,6) =  parameters[0]*y[72]*exp(-parameters[5]*(1.0/y[73]-1.0));
  JAC(75,6) =  parameters[0]*y[74]*exp(-parameters[5]*(1.0/y[75]-1.0));
  JAC(77,6) =  parameters[0]*y[76]*exp(-parameters[5]*(1.0/y[77]-1.0));
  JAC(79,6) =  parameters[0]*y[78]*exp(-parameters[5]*(1.0/y[79]-1.0));
  JAC(81,6) =  parameters[0]*y[80]*exp(-parameters[5]*(1.0/y[81]-1.0));
  JAC(83,6) =  parameters[0]*y[82]*exp(-parameters[5]*(1.0/y[83]-1.0));
  JAC(85,6) =  parameters[0]*y[84]*exp(-parameters[5]*(1.0/y[85]-1.0));
  JAC(87,6) =  parameters[0]*y[86]*exp(-parameters[5]*(1.0/y[87]-1.0));
  JAC(89,6) =  parameters[0]*y[88]*exp(-parameters[5]*(1.0/y[89]-1.0));
  JAC(91,6) =  parameters[0]*y[90]*exp(-parameters[5]*(1.0/y[91]-1.0));
  JAC(93,6) =  parameters[0]*y[92]*exp(-parameters[5]*(1.0/y[93]-1.0));
  JAC(95,6) =  parameters[0]*y[94]*exp(-parameters[5]*(1.0/y[95]-1.0));
  JAC(97,6) =  parameters[0]*y[96]*exp(-parameters[5]*(1.0/y[97]-1.0));
  JAC(99,6) =  parameters[0]*y[98]*exp(-parameters[5]*(1.0/y[99]-1.0));
}